module.exports = function (app) {
  // prometheus monitoring setup
  let { client, metricsCounters } = app.promMetric;

  metricsCounters = {
    ...metricsCounters,
    ...{
      dbMigrationFailed: new client.Counter({
        name: 'db_migration_failed',
        help: 'Number of database migration failure.',
        labelNames: ['db', 'severity']
      }),
      httpCall: new client.Counter({
        name: 'http_call_total',
        help: 'A call to another HTP service.',
        labelNames: ['pool']
      }),
      httpCallElapsedMs: new client.Histogram({
        name: 'http_call_elapsed_ms',
        help: 'Time elapsed in ms to make a call to another HTTP service.',
        labelNames: ['pool']
      }),
      httpError: new client.Counter({
        name: 'http_errors_total',
        help: 'An error response from another HTTP service.',
        labelNames: ['pool', 'status']
      }),
      httpRetry: new client.Counter({
        name: 'http_retries_total',
        help: 'A failed HTTP request was retried.',
        labelNames: ['pool']
      }),
      httpConcurrentCalls: new client.Gauge({
        name: 'http_concurrent_calls',
        help: 'Number of HTTP calls in progress at any given time.',
        labelNames: ['pool']
      }),
      redisHit: new client.Counter({
        name: 'redis_hit',
        help: 'A hit against remote L2 Redis cache.',
        labelNames: ['objectType']
      }),
      redisPut: new client.Counter({
        name: 'redis_put',
        help: 'A put to remote L2 Redis cache.',
        labelNames: ['objectType']
      }),
      redisMiss: new client.Counter({
        name: 'redis_miss',
        help: 'A miss against remote L2 Redis cache.',
        labelNames: ['objectType']
      }),
      redisClear: new client.Counter({
        name: 'redis_clear',
        help: 'A clear key against remote L2 Redis cache.',
        labelNames: ['objectType']
      }),
      redisDropped: new client.Counter({
        name: 'redis_dropped',
        help: 'The redis connection dropped.',
        labelNames: ['code']
      }),
      redisError: new client.Counter({
        name: 'redis_error',
        help: 'An error using Redis.'
      }),
      redisElapsedMs: new client.Histogram({
        name: 'redis_elapsed_ms',
        help: 'Time elapsed in ms to fetch from Redis cache.',
        labelNames: ['objectType']
      }),
      messageEmitted: new client.Counter({
        name: 'message_total',
        help: 'A message emitted to the queue'
      }),
      messageFailed: new client.Counter({
        name: 'message_errors_total',
        help: 'A message failure. Message was not emitted to queue.'
      }),
      auditLog: new client.Counter({
        name: 'audit_log_total',
        help: 'An entry logged to the audit database'
      }),
      auditLogFailed: new client.Counter({
        name: 'audit_log_error_total',
        help: 'An error logging to the audit database'
      }),
      auditReadEvent: new client.Counter({
        name: 'audit_read_event_total',
        help: 'A READ audit event emitted. Used to measure read event volume before enabling full read audit logging.',
        labelNames: ['resourceType', 'orgId']
      }),
      socialPublishRenditionMiss: new client.Counter({
        name: 'social_publish_rendition_miss_total',
        help:
          'distributeAsset (VE-26886) found no publish-suitable Master/Proxy dmh-rendition. reason=no_renditions: ' +
          'TDO has no dmh-renditions, fell back to the primary media asset (expected for non-DMH content). ' +
          'reason=no_suitable: renditions present but none publishable, mutation rejected with resource_conflict ' +
          '(data.retryable says whether a Master/Proxy may still land). reason=lookup_error: the TDO\'s recording_asset ' +
          'partition does not exist (TDO predates the asset store), fell back to the primary media asset; any other ' +
          'asset-store failure fails the mutation instead. Alert on no_suitable and lookup_error.',
        labelNames: ['reason']
      }),
      unexpectedError: new client.Counter({
        name: 'unexpected_errors_total',
        help: 'An unexpected error condition that might indicate an outage.',
        labelNames: ['operation']
      }),
      fatalError: new client.Counter({
        name: 'fatal_errors_total',
        help:
          'An incidence of an error condition that, if repeated, will cause server to exit.'
      }),
      outOfBandError: new client.Counter({
        name: 'out_of_band_errors_total',
        help: 'An error that occurred out-of-band.'
      }),
      timeoutError: new client.Counter({
        name: 'timeout_errors_total',
        help: 'A timeout error generated by the server',
        labelNames: ['operation', 'operationType']
      }),
      awsURLSignError: new client.Counter({
        name: 'aws_url_sign_error',
        help: 'An error getting a signed URL from the AWS SDK'
      }),
      awsURLSignError10Sec: new client.Gauge({
        name: 'aws_url_sign_error_10s',
        help:
          'An error getting a signed URL from the AWS SDK over 10 second window'
      }),
      awsUploadError: new client.Counter({
        name: 'aws_upload_error',
        help: 'Error when uploading file stream from AWS SDK'
      }),
      memGC: new client.Counter({
        name: 'mem_garbage_collect',
        help: 'A garbage collection event.'
      }),
      memLeak: new client.Counter({
        name: 'mem_leak',
        help: 'A potential memory leak detected.'
      }),
      healthCheckFailed: new client.Counter({
        name: 'health_check_failed',
        help: 'A server health check failed.',
        labelNames: ['status']
      }),
      healthCheckOk: new client.Counter({
        name: 'health_check_ok',
        help: 'A server health check passed.'
      }),
      queryMonLongQueries: new client.Counter({
        name: 'query_monitor_long_queries',
        help: 'A long-running database query',
        labelNames: ['database']
      }),
      queryMonKilledQueries: new client.Counter({
        name: 'query_monitor_killed_queries',
        help: 'A long-running database query that was killed',
        labelNames: ['database']
      }),
      queryMonTerminatedQueries: new client.Counter({
        name: 'query_monitor_terminated_queries',
        help: 'A long-running database query that was terminated',
        labelNames: ['database']
      }),
      queryMonKillFailures: new client.Counter({
        name: 'query_monitor_kill_failures',
        help: 'A long-running database query that could not be killed',
        labelNames: ['database']
      }),
      queryMonErrors: new client.Counter({
        name: 'query_monitor_errors',
        help:
          'Query monitor was not able to successfully query a database for long-running queries',
        labelNames: ['database']
      }),
      analyzeMonTables: new client.Counter({
        name: 'analyze_monitor_tables',
        help: 'A stale table that was successfully analyzed',
        labelNames: ['database']
      }),
      analyzeMonErrors: new client.Counter({
        name: 'analyze_monitor_errors',
        help:
          'Analyze monitor was not able to discover stale tables or analyze one of them',
        labelNames: ['database']
      }),
      internalTokenError: new client.Counter({
        name: 'internal_token_error',
        help:
          'A system component running with an internal token encountered an error.'
      }),
      engineJWTError: new client.Counter({
        name: 'engine_jwt_error',
        help: 'An engine running with a JWT encountered an error.'
      }),
      criticalOrgError: new client.Counter({
        name: 'critical_org_error',
        help:
          'ANY error encountered by API key for a critical customer organization',
        labelNames: ['errorName', 'orgId']
      }),
      rateLimitError: new client.Counter({
        name: 'rate_limit_error',
        help: 'A request was denied due to rate limit enforcement.',
        labelNames: ['reason'] // org_limit, token_limit, server_health, etc.
      }),
      graphQLQueryCostWarning: new client.Counter({
        name: 'graphql_query_cost_warning',
        help: 'A client made potentially costly GraphQL query.'
      }),
      graphQLQueryDeprecatedAPIWarning: new client.Counter({
        name: 'graphql_query_deprecated_api_warning',
        help: 'A client used a deprecated API type, field, or parameter.',
        labelNames: ['api']
      }),
      graphQLQueryExpiredAPIWarning: new client.Counter({
        name: 'graphql_query_expired_api_warning',
        help:
          'A client used a deprecated API type, field, or parameter ' +
          'that has expired and can no longer be used.',
        labelNames: ['api']
      }),
      // VE-26450: pre-flight media-constraint outcomes at the distributeAsset mutation. Labelled by platform and
      // constraint only — deliberately NOT by org or TDO id, which would explode metric cardinality; those belong
      // in logs and traces. The rejection counter answers "how much did this prevent?", and a mis-declared
      // constraint that starts blocking valid publishes shows up here rather than silently. The fallthrough
      // counter is the necessary companion: it measures how often enforcement did not apply because the asset had
      // no duration, without which a flat rejection count is indistinguishable from a check that never ran.
      distributeMediaConstraintEvaluated: new client.Counter({
        name: 'graphql_distribute_media_constraint_evaluated',
        help:
          'A distributeAsset publish reached the pre-flight media-constraint check with a declared constraint ' +
          'to evaluate. This is the DENOMINATOR for the rejection and fallthrough counters: without it a ' +
          'rejection spike cannot be distinguished from a publish-volume spike, so neither counter is ' +
          'alertable as a rate.',
        labelNames: ['platform']
      }),
      distributeMediaConstraintRejection: new client.Counter({
        name: 'graphql_distribute_media_constraint_rejection',
        help:
          'A distributeAsset publish was rejected pre-flight for violating a declared media constraint.',
        labelNames: ['platform', 'constraint']
      }),
      distributeMediaConstraintFallthrough: new client.Counter({
        name: 'graphql_distribute_media_constraint_fallthrough',
        help:
          'A distributeAsset publish skipped a declared media-constraint check and fell through to the vendor ' +
          'rejection backstop. The `reason` label distinguishes benign causes (duration_unknown — not yet ' +
          'stamped by the ffprobe pass; ambiguous_media_asset; ambiguous_post_type) from INFRASTRUCTURE ' +
          'FAILURE (duration_unreadable, constraints_unreadable — a database read failed) and from a DEFECT in ' +
          'the check itself (check_failed — it threw something that was not a verdict). A sustained rise in ' +
          'the latter three means enforcement is silently not running and should be triaged, not ignored; ' +
          'check_failed should be zero and any occurrence is a bug.',
        // `reason` deliberately differs from the rejection counter's `constraint`: these are skip reasons, not
        // constraint classes (ambiguous_post_type is not a constraint), so one shared label name would make a
        // `sum by (...)` across the two metrics compare unlike things.
        labelNames: ['platform', 'reason']
      }),
      meteredEvent: new client.Counter({
        name: 'graphql_metered_event',
        help: 'A metered event was emitted.'
      }),
      meteredEventError: new client.Counter({
        name: 'graphql_metered_event_error',
        help: 'An error was encountered emitting a metered event.'
      }),
      addMediaSegments: new client.Histogram({
        name: 'graphql_addmediasegments_elapsed',
        help: 'Time elapsed addMediaSegments.',
        labelNames: ['operation']
      }),
      graphqlQueries: new client.Counter({
        name: 'graphql_queries_total',
        help: 'GraphQL queries with their minified representation.',
        labelNames: ['request']
      }),
      graphqlQueriesElapsedMs: new client.Histogram({
        name: 'graphql_queries_elapsed_ms',
        help: 'Graphql query timing',
        labelNames: ['request'],
        buckets: [
          10,
          100,
          250,
          500,
          1000,
          3000,
          5000,
          10000,
          20000,
          30000,
          50000,
          70000,
          100000,
          130000
        ]
      }),
      graphqlFieldStatsElapsedMs: new client.Histogram({
        name: 'graphql_queries_field_stats_elapsed_ms',
        help: 'Graphql resolver fields timing',
        labelNames: ['field'],
        buckets: [
          10,
          100,
          250,
          500,
          1000,
          2000,
          3500,
          5000,
          7500,
          10000,
          20000,
          30000,
          40000,
          50000,
          60000
        ]
      }),
      engineResultAssetsPerQuery: new client.Histogram({
        name: 'engine_result_assets_per_query',
        help: 'vtn-standard assets fanned out by one engineResults query.',
        buckets: [1, 2, 5, 10, 25, 50, 100, 250, 500, 1000]
      }),
      // graphqlFieldStatsElapsedMs above records each field's MEAN
      // once per request, so a field resolved 50 times in one request looks
      // identical to one resolved once.
      //   rate(graphql_field_resolutions_total[5m])
      //     / rate(graphql_queries_field_stats_elapsed_ms_count[5m])
      // A ratio near 1 is a normal field; a ratio of 30 is a per-parent
      // resolver (Source.sourceType) or an aliased batch query.
      graphqlFieldResolutions: new client.Counter({
        name: 'graphql_field_resolutions_total',
        help: 'Total resolutions of a field, summed across requests.',
        labelNames: ['field']
      }),
      graphqlFieldResponseBytes: new client.Counter({
        name: 'graphql_field_response_bytes_total',
        help: 'Total bytes contributed by a field, summed across requests.',
        labelNames: ['field']
      }),
      graphqlResponseSizeBytes: new client.Histogram({
        name: 'graphql_response_size_bytes',
        help: 'Total response size in bytes for one GraphQL request.',
        buckets: [1024, 10240, 102400, 1048576, 10485760, 52428800, 104857600]
      }),
      graphqlQueryCost: new client.Histogram({
        name: 'graphql_query_cost',
        help: 'Computed cost of one GraphQL request (sum of field limits).',
        buckets: [10, 50, 100, 250, 500, 750, 1000, 2000, 5000, 10000]
      }),
      resolverCacheHit: new client.Counter({
        name: 'resolver_cache_hits_total',
        help: 'Request-scoped resolver cache hit.',
        labelNames: ['objectType']
      }),
      resolverCacheMiss: new client.Counter({
        name: 'resolver_cache_misses_total',
        help: 'Request-scoped resolver cache miss.',
        labelNames: ['objectType']
      }),
      sqlSlowQuery: new client.Counter({
        name: 'sql_slow_queries_total',
        help: 'A SQL statement exceeding the slow-query threshold.',
        labelNames: ['db', 'table', 'op']
      }),
      tdoCleanupAssets: new client.Histogram({
        name: 'tdo_cleanup_assets',
        help: 'Assets enumerated for deletion by one TDO cleanup.',
        buckets: [1, 2, 5, 10, 30, 60, 150, 300, 1000, 5000]
      })

      /*
    operation: new client.Counter({
      name: 'graphql_operations_total',
      help:
        'A GraphQL operation (query or mutation). A single request can specify multiple operations.',
      labelNames: ['type']
    }),
    request: new client.Counter({
      name: 'graphql_requests_total',
      help: 'A single request received by the GraphQL server.',
      labelNames: ['method']
    }),

    error: new client.Counter({
      name: 'graphql_errors_total',
      help: 'An error encountered while processing a client request.'
    }),

    fieldTimeElapsedMs: new client.Histogram({
      name: 'graphql_resolver_time_elapsed_ms',
      help:
        'Time elapsed in ms to resolve a single non-trivial field in a GraphQL query. ' +
        'A single operation typically includes multiple fields.',
      buckets: [
        1,
        10,
        100,
        250,
        500,
        1000,
        2000,
        3500,
        5000,
        7500,
        10000,
        20000,
        30000,
        40000,
        50000,
        60000
      ],
      labelNames: ['type']
    }),
    requestTimeElapsedMs: new client.Histogram({
      name: 'graphql_request_time_elapsed_ms',
      help:
        'Time required in ms for the GraphQL server to fulfill a single request.',
      buckets: [
        1,
        10,
        100,
        250,
        500,
        1000,
        2000,
        3500,
        5000,
        7500,
        10000,
        20000,
        30000,
        40000,
        50000,
        60000,
        90000,
        120000,
        180000
      ],
      labelNames: ['method']
    }),
    concurrentRequests: new client.Gauge({
      name: 'graphql_concurrent_requests',
      help: 'Number of client requests in progress at any given time.'
    })
  */
    },
    graphqlCreatedSDO: new client.Counter({
      name: 'graphql_created_sdo',
      help: 'A SDO was created.'
    }),
    graphqlUpdatedSDO: new client.Counter({
      name: 'graphql_updated_sdo',
      help: 'A SDO was updated.'
    }),

    // -----------------------------------------------------------------------
    // Virtual Asset & Presigner metrics
    // -----------------------------------------------------------------------
    virtualAssetCreatedTotal: new client.Counter({
      name: 'virtual_asset_created_total',
      help: 'Number of virtual asset JWTs generated during GraphQL resolution'
    }),
    virtualAssetRedirectTotal: new client.Counter({
      name: 'virtual_asset_redirect_total',
      help: 'Number of virtual asset redirects served, labeled by outcome',
      labelNames: ['outcome']
    }),
    virtualAssetRedirectLatencyMs: new client.Histogram({
      name: 'virtual_asset_redirect_latency_ms',
      help: 'Time from JWT verification to 302 response',
      buckets: [5, 10, 25, 50, 100, 250, 500, 1000, 2500, 5000, 10000]
    }),
    presignerHeadCheckTotal: new client.Counter({
      name: 'presigner_head_check_total',
      help: 'Number of HEAD checks performed, labeled by result',
      labelNames: ['result']
    }),
    presignerHeadCheckLatencyMs: new client.Histogram({
      name: 'presigner_head_check_latency_ms',
      help: 'HEAD check round-trip time',
      buckets: [5, 10, 25, 50, 100, 250, 500, 1000, 2000, 3000, 5000]
    }),
    presignerHeadCacheTotal: new client.Counter({
      name: 'presigner_head_cache_total',
      help: 'Object-existence cache lookups on the signing hot path, labeled by result (l1_hit=in-proc, l2_hit=shared redis, origin=object-store HEAD)',
      labelNames: ['result']
    }),
    presignerFallbackTotal: new client.Counter({
      name: 'presigner_fallback_total',
      help: 'Number of times a fallback presigner was used instead of the primary'
    }),
    presignerFallbackRatio: new client.Gauge({
      name: 'presigner_fallback_ratio',
      help: 'Ratio of fallback-signed URLs to primary-signed URLs (indicates migration progress)'
    }),
    assetUriPromotedTotal: new client.Counter({
      name: 'asset_uri_promoted_total',
      help: 'Number of updateAssetUri calls (DB record promotions)'
    }),
    assetUriPromotionErrorTotal: new client.Counter({
      name: 'asset_uri_promotion_error_total',
      help: 'Number of updateAssetUri failures (DB record promotion errors)'
    }),
    virtualAssetFeatureEnabled: new client.Gauge({
      name: 'virtual_asset_feature_enabled',
      help: 'Whether virtualAssetEnabled feature flag is set (1=enabled, 0=disabled)'
    }),

    // WebSocket subscription protocol metrics (STWS baseline)
    wsConnections: new client.Counter({
      name: 'graphql_ws_connections_total',
      help: 'Total WebSocket connections by protocol.',
      labelNames: ['protocol']
    }),
    wsDisconnections: new client.Counter({
      name: 'graphql_ws_disconnections_total',
      help: 'Total WebSocket disconnections by protocol.',
      labelNames: ['protocol']
    }),
    wsActiveConnections: new client.Gauge({
      name: 'graphql_ws_active_connections',
      help: 'Currently active WebSocket connections by protocol.',
      labelNames: ['protocol']
    }),
    // NOTE: operation label intentionally omitted — client-supplied operationName is unbounded
    // and would cause high-cardinality time series. Use logs for per-operation visibility.
    wsSubscriptions: new client.Counter({
      name: 'graphql_ws_subscriptions_total',
      help: 'Total subscription operations started by protocol.',
      labelNames: ['protocol']
    }),
    wsErrors: new client.Counter({
      name: 'graphql_ws_errors_total',
      help: 'Total WebSocket errors by protocol.',
      labelNames: ['protocol']
    })
  };

  return {
    metricsCounters
  };
};
