INSERT INTO public.application (
  application_id,
  application_name,
  application_key,
  application_status,
  application_description,
  application_icon_url,
  application_icon_svg,
  application_url,
  application_check_permissions,
  application_order,
  owner_organization_id,
  deployment_model,
  created_date,
  updated_date,
  oauth2_redirect_urls,
  oauth2_client_secret,
  permissions_required
) SELECT
  '5704cfc1-799f-422d-bc98-25b1083f37f9', 
  'IDentify', 
  'seta_facet_match_prod_app',
  'active', 
  'Organize case files, find faces in media files, and compare against databases of known offenders and persons of interest',
  'https://static.veritone.com/veritone-ui/appicons-2/identify.png',
  NULL,
  'https://identify.@@{EXTERNAL_DNS_ZONE}@@',
  false,
  0,
  1,
  0,
  1532454734,
  1594912008,
  'https://identify.@@{EXTERNAL_DNS_ZONE}@@',
  'TwvsSgJqgS16WkcKmUav1sctNcMQri2LQzIotMcUIZtBJVp9UKWc9Q',
  NULL
WHERE NOT EXISTS (SELECT 1 FROM public.application WHERE application_id = '5704cfc1-799f-422d-bc98-25b1083f37f9');
