-- VE-13027

-- Update application icons and SVGs for core applications to utilize static cdn

UPDATE public.application SET application_icon_url = 'https://get.aiware.com/static/app-icons/Admin@2x.png', application_icon_svg = 'https://get.aiware.com/static/app-icons/Admin.svg' WHERE application_id = 'ea1d26ab-0d29-4e97-8ae7-d998a243374e';
UPDATE public.application SET application_icon_url = 'https://get.aiware.com/static/app-icons/Attribute@2x.png', application_icon_svg = 'https://get.aiware.com/static/app-icons/Attribute.svg' WHERE application_id = '2d6e9991-e551-458c-9e9c-0c70aeaea456';
UPDATE public.application SET application_icon_url = 'https://get.aiware.com/static/app-icons/Automate@2x.png', application_icon_svg = 'https://get.aiware.com/static/app-icons/Automate.svg' WHERE application_id = 'bdf9375e-1092-4233-8197-9ccbc11357c5';
UPDATE public.application SET application_icon_url = 'https://get.aiware.com/static/app-icons/Benchmark@2x.png', application_icon_svg = 'https://get.aiware.com/static/app-icons/Benchmark.svg' WHERE application_id = '865f0dc3-393b-4c83-8c90-3e0f0a3a18d2';
UPDATE public.application SET application_icon_url = 'https://get.aiware.com/static/app-icons/Analytics@2x.png', application_icon_svg = 'https://get.aiware.com/static/app-icons/Analytics.svg' WHERE application_id = 'f6383434-f45c-4174-a760-b09f5158082e';
UPDATE public.application SET application_icon_url = 'https://get.aiware.com/static/app-icons/Collections@2x.png', application_icon_svg = 'https://get.aiware.com/static/app-icons/Collections.svg' WHERE application_id = 'cc4e0e89-3420-49c2-b06d-8d9a929c941c';
UPDATE public.application SET application_icon_url = 'https://get.aiware.com/static/app-icons/Data_Center@2x.png', application_icon_svg = 'https://get.aiware.com/static/app-icons/Data_Center.svg' WHERE application_id = '8a37c1d0-3f3b-48d0-a84e-2b8e3646fbe5';
UPDATE public.application SET application_icon_url = 'https://get.aiware.com/static/app-icons/Developer@2x.png', application_icon_svg = 'https://get.aiware.com/static/app-icons/Developer.svg' WHERE application_id = 'b9dba7b8-501a-4219-995b-5e6eadfb5ae0';
UPDATE public.application SET application_icon_url = 'https://get.aiware.com/static/app-icons/Discovery@2x.png', application_icon_svg = 'https://get.aiware.com/static/app-icons/Discovery.svg' WHERE application_id = '32babe30-fb42-11e4-89bc-27b69865858a';
UPDATE public.application SET application_icon_url = 'https://get.aiware.com/static/app-icons/DMH_Admin@2x.png', application_icon_svg = 'https://get.aiware.com/static/app-icons/DMH_Admin.svg' WHERE application_id = 'c4c3caf8-2031-4a88-aa40-ed67c822050e';
UPDATE public.application SET application_icon_url = 'https://get.aiware.com/static/app-icons/Cheat-Sheet@2x.png', application_icon_svg = 'https://get.aiware.com/static/app-icons/Cheat-Sheet.svg' WHERE application_id = 'a3589461-a61b-4cd4-be0b-e007ffbdfd83';
UPDATE public.application SET application_icon_url = 'https://get.aiware.com/static/app-icons/Identify@2x.png', application_icon_svg = 'https://get.aiware.com/static/app-icons/Identify.svg' WHERE application_id = '5704cfc1-799f-422d-bc98-25b1083f37f9';
UPDATE public.application SET application_icon_url = 'https://get.aiware.com/static/app-icons/Illuminate@2x.png', application_icon_svg = 'https://get.aiware.com/static/app-icons/Illuminate.svg' WHERE application_id = '8b3eac1c-5150-448e-8d99-fb7b860e7e41';
UPDATE public.application SET application_icon_url = 'https://get.aiware.com/static/app-icons/K1@2x.png', application_icon_svg = 'https://get.aiware.com/static/app-icons/K1.svg' WHERE application_id = '557810e9-f38f-40de-991d-e0adff77cb86';
UPDATE public.application SET application_icon_url = 'https://get.aiware.com/static/app-icons/Library@2x.png', application_icon_svg = 'https://get.aiware.com/static/app-icons/Library.svg' WHERE application_id = 'cf05552b-52e0-46fa-8f7f-4c9eee135c51';
UPDATE public.application SET application_icon_url = 'https://get.aiware.com/static/app-icons/Media_Processing@2x.png', application_icon_svg = 'https://get.aiware.com/static/app-icons/Media_Processing.svg' WHERE application_id = '6975ecbb-ec36-4c3c-b399-bb288259db48';
UPDATE public.application SET application_icon_url = 'https://get.aiware.com/static/app-icons/Pay@2x.png', application_icon_svg = 'https://get.aiware.com/static/app-icons/Pay.svg' WHERE application_id = '4a30782e-2808-487b-a359-bc50247af31d';
UPDATE public.application SET application_icon_url = 'https://get.aiware.com/static/app-icons/Qlik@2x.png', application_icon_svg = 'https://get.aiware.com/static/app-icons/Qlik.svg' WHERE application_id = '99bebebc-2f7c-4f63-ab19-562297d47bde';
UPDATE public.application SET application_icon_url = 'https://get.aiware.com/static/app-icons/Redact@2x.png', application_icon_svg = 'https://get.aiware.com/static/app-icons/Redact.svg' WHERE application_id = '766e9916-9536-47e9-8dcb-dc225654bab3';
UPDATE public.application SET application_icon_url = 'https://get.aiware.com/static/app-icons/Wyvern@2x.png', application_icon_svg = 'https://get.aiware.com/static/app-icons/Wyvern.svg' WHERE application_id = '931c11d3-9639-4bd0-88e7-9bfac25e61b7';
UPDATE public.application SET application_icon_url = 'https://get.aiware.com/static/app-icons/Redact_Suspect@2x.png', application_icon_svg = 'https://get.aiware.com/static/app-icons/Redact_Suspect.svg' WHERE application_id = 'b05ed6eb-2783-4407-a159-c5b265756a3a';
UPDATE public.application SET application_icon_url = 'https://get.aiware.com/static/app-icons/Blackbird@2x.png', application_icon_svg = 'https://get.aiware.com/static/app-icons/Blackbird.svg' WHERE application_id = '3702308f-08b2-42c0-8358-c5da8b64ba76';
UPDATE public.application SET application_icon_url = 'https://get.aiware.com/static/app-icons/Surveillance2@2x.png', application_icon_svg = 'https://get.aiware.com/static/app-icons/Surveillance2.svg' WHERE application_id = 'ccd417d8-5dce-4b13-81e1-3bb88a290a25';
UPDATE public.application SET application_icon_url = 'https://get.aiware.com/static/app-icons/Surveillance2@2x.png', application_icon_svg = 'https://get.aiware.com/static/app-icons/Surveillance2.svg' WHERE application_id = '60d04a15-af56-4f8f-85c6-dd7e419de08f';
UPDATE public.application SET application_icon_url = 'https://get.aiware.com/static/app-icons/K2@2x.png', application_icon_svg = 'https://get.aiware.com/static/app-icons/K2.svg' WHERE application_id = 'caf06532-6787-45f3-a2e4-8ff02a55012f';
UPDATE public.application SET application_icon_url = 'https://get.aiware.com/static/app-icons/Analytics@2x.png', application_icon_svg = 'https://get.aiware.com/static/app-icons/Analytics.svg' WHERE application_id = 'bc519e7f-7953-408d-8991-57f217286d6c';
UPDATE public.application SET application_icon_url = 'https://get.aiware.com/static/app-icons/Collections@2x.png', application_icon_svg = 'https://get.aiware.com/static/app-icons/Collections.svg' WHERE application_id = 'cc4e0e89-3420-49c2-b06d-8d9a929c941c';
UPDATE public.application SET application_icon_url = 'https://get.aiware.com/static/app-icons/Discovery@2x.png', application_icon_svg = 'https://get.aiware.com/static/app-icons/Discovery.svg' WHERE application_id = '32babe30-fb42-11e4-89bc-27b69865858a';
UPDATE public.application SET application_icon_url = 'https://get.aiware.com/static/app-icons/Developer@2x.png', application_icon_svg = 'https://get.aiware.com/static/app-icons/Developer.svg' WHERE application_id = '732c697a-0eb1-4c92-9c40-5d6f5dab8baa';
UPDATE public.application SET application_icon_url = 'https://get.aiware.com/static/app-icons/Identify@2x.png', application_icon_svg = 'https://get.aiware.com/static/app-icons/Identify.svg' WHERE application_id = '5704cfc1-799f-422d-bc98-25b1083f37f9';
UPDATE public.application SET application_icon_url = 'https://get.aiware.com/static/app-icons/Analytics@2x.png', application_icon_svg = 'https://get.aiware.com/static/app-icons/Analytics.svg' WHERE application_id = 'a1ed9b40-0193-431a-98e5-c1c22e211058';
UPDATE public.application SET application_icon_url = 'https://get.aiware.com/static/app-icons/Hub.png', application_icon_svg = NULL WHERE application_id = '9b774b0e-a5b1-452c-a0aa-4e2e64ead2b3';
UPDATE public.application SET application_icon_url = 'https://get.aiware.com/static/app-icons/aiware_desktop_app_icon.png', application_icon_svg = NULL WHERE application_id = 'e4739d44-53d2-4153-b55f-5e246fc989b1';
UPDATE public.application SET application_icon_url = 'https://get.aiware.com/static/app-icons/Graphql-logo.png', application_icon_svg = NULL WHERE application_id = '457715e0-06ff-47c3-a8bf-e67a73c4cfe4';
UPDATE public.application SET application_icon_url = 'https://get.aiware.com/static/app-icons/advertiser.png', application_icon_svg = NULL WHERE application_id = '7f402a84-4ae6-451f-85ca-9447397610b7';

