-- Build 2
INSERT INTO job_new.build
(engine_id, build_id, "version", "build_state", 
    price, created_date, updated_date, deployment_model, docker_image, task_runtime, is_legacy, vul_low_count, vul_medium_count, vul_high_count, vul_critical_count, build_size, deploy_date, manifest, data_certified, release_notes)
SELECT '8fad081b-fbac-445f-afde-a3f8a53a55ee', '5aca7073-92f2-426a-82b1-bcd4b2c56a78', 2, 'deployed'::build_state, NULL, 1651702612, 1651702612, 0, 'registry.central.aiware.com/d12e8f6d-9285-4f7d-aa2e-9e6151206277:a0e56e83-6b2d-47b7-80e6-095d740b9aca', '{"edge": {}}'::jsonb, false, NULL, NULL, NULL, NULL, NULL, NULL, '{"url": "https://github.com/veritone/google-speech-chunk-v3", "user": "qdang+superadmin@veritone.com", "build": "5aca7073-92f2-426a-82b1-bcd4b2c56a78", "oauth": "", "runtime": "", "category": "transcription", "engineId": "8fad081b-fbac-445f-afde-a3f8a53a55ee", "isPublic": true, "schedule": "", "schemaId": 0, "sourceId": 0, "ingestion": {"scanner": false, "supportsLiveStreams": false, "supportedSourceTypes": null}, "libraries": null, "maxFileMb": 0, "categories": null, "engineMode": "chunk", "clusterSize": "small", "isBenchmark": false, "isConductor": false, "useCustomUI": false, "gpuSupported": "", "inputOptions": null, "releaseNotes": "", "customProfile": "", "externalCalls": [], "inputEncoding": "", "outputFormats": ["application/json"], "serverCountry": "", "volumeProfile": "", "maxConcurrency": 50, "isCJISCompliant": false, "trainableViaApi": false, "whitelistOrgIds": null, "maxMediaLengthMs": 0, "minMediaLengthMs": 0, "fedRampImpactLevel": 0, "initialConcurrency": 50, "sourceFileDeletion": false, "supportedLanguages": null, "preferredInputFormat": "audio/wav", "supportedInputFormats": ["audio/wav"]}'::jsonb, NULL, NULL

ON CONFLICT DO NOTHING;

-- Build 1
INSERT INTO job_new.build
(engine_id, build_id, "version", "build_state", price, created_date, updated_date, deployment_model, docker_image, task_runtime, is_legacy, vul_low_count, vul_medium_count, vul_high_count, vul_critical_count, build_size, deploy_date, manifest, data_certified, release_notes)

SELECT '8fad081b-fbac-445f-afde-a3f8a53a55ee', 'adf4e54a-36f1-4421-bb44-73ac8d375e91', 1, 'approved'::build_state, NULL, 1651699946, 1651699946, 0, 'registry.central.aiware.com/d12e8f6d-9285-4f7d-aa2e-9e6151206277:a5d5ff62-2908-4046-b108-39f1cd9971e9', '{"edge": {}}'::jsonb, false, NULL, NULL, NULL, NULL, NULL, NULL, '{"url": "https://github.com/veritone/google-speech-chunk-v3", "user": "qdang+superadmin@veritone.com", "build": "adf4e54a-36f1-4421-bb44-73ac8d375e91", "oauth": "", "runtime": "", "category": "transcription", "engineId": "8fad081b-fbac-445f-afde-a3f8a53a55ee", "isPublic": true, "schedule": "", "schemaId": 0, "sourceId": 0, "ingestion": {"scanner": false, "supportsLiveStreams": false, "supportedSourceTypes": null}, "libraries": null, "maxFileMb": 0, "categories": null, "engineMode": "chunk", "clusterSize": "small", "isBenchmark": false, "isConductor": false, "useCustomUI": false, "gpuSupported": "", "inputOptions": null, "releaseNotes": "", "customProfile": "", "externalCalls": [], "inputEncoding": "", "outputFormats": ["application/json"], "serverCountry": "", "volumeProfile": "", "maxConcurrency": 50, "isCJISCompliant": false, "trainableViaApi": false, "whitelistOrgIds": null, "maxMediaLengthMs": 0, "minMediaLengthMs": 0, "fedRampImpactLevel": 0, "initialConcurrency": 50, "sourceFileDeletion": false, "supportedLanguages": null, "preferredInputFormat": "audio/wav", "supportedInputFormats": ["audio/wav"]}'::jsonb, NULL, NULL

ON CONFLICT DO NOTHING;