-- VE-18814 Add the S3DAv2 engine (builds will be added by Repeatable script
-- R__65__update_s3_discovery_adapter_build.sql)

INSERT INTO job_new.engine(
  engine_id,
  engine_category_id,
  engine_name,
  engine_description,
  engine_state,
  deployment_model,
  owner_organization_id,
  is_public,
  fields,
  creates_recording,
  deleted,
  created_date,
  updated_date,
  library_required,
  icon_path,
  jwt_rights,
  use_cases,
  industries,
  engine_manifest,
  edge_version,
  distribution_type
) VALUES (
  '785a19e5-c2ef-4d0a-b40c-357f47eefa26', 
  '4b150c85-82d0-4a18-b7fb-63e4a58dfcce', 
  'S3 Discovery Adapter v2', 
  'Discovers individual files or scans an S3 bucket (with optional filters) for files. An ingest slug is created for each discovered file. Optimized for high discovery throughput.', 
  'active'::public.engine_state, 
  2, 
  @@{ROOT_ORG_ID}@@,
  true, 
  '[{"info": "Access key to access the S3 bucket (used with the secretKey). Optional if the media source for this bucket has credentials.", "name": "accessKey", "type": "text", "label": "Access Key", "value": "", "required": false, "defaultValue": ""}, {"info": "Secret key to access the S3 bucket (used with accessKey). Optional if the media source for this bucket has credentials.", "name": "secretKey", "type": "text", "label": "Secret Key", "value": "", "required": false, "defaultValue": ""}, {"info": "AWS region the bucket is in. Optional if the media source for this bucket has credentials.", "name": "region", "type": "text", "label": "Region", "value": "", "required": false, "defaultValue": ""}, {"info": "URI of a file to discover (like s3://bucket/path/key)", "name": "s3URI", "type": "text", "label": "S3 URI", "value": "", "required": false, "defaultValue": ""}, {"info": "Name of S3 Bucket to look for file in. Used with s3Key", "name": "s3Bucket", "type": "text", "label": "S3 Bucket", "value": "", "required": false, "defaultValue": ""}, {"info": "Object key to discover. Used with s3Bucket", "name": "s3Key", "type": "text", "label": "S3 Key", "value": "", "required": false, "defaultValue": ""}, {"info": "List of S3 URIs to discover, like \"s3://bucket/key1 s3://bucket/key2\"", "name": "s3URIs", "type": "text", "label": "S3 URIs", "value": "", "required": false, "defaultValue": ""}, {"info": "Name of S3 Bucket to scan for files to discover.", "name": "s3ScanBucket", "type": "text", "label": "S3 Scan Bucket", "value": "", "required": false, "defaultValue": ""}, {"info": "Prefix of object keys to filter on.", "name": "s3ScanPrefix", "type": "text", "label": "S3 Scan Prefix", "value": "", "required": false, "defaultValue": ""}, {"info": "RE2 regular expression for files to discover. Files matching this regular expression will be included unless they also match the excludeRegex. If not provided, all files will be discovered.", "name": "s3ScanIncludeRegex", "type": "text", "label": "Include Regular Expression", "value": "", "required": false, "defaultValue": ""}, {"info": "RE2 regular expression for files to ignore during discovery. Files matching this regular expression will be excluded. If not provided, no files will be excluded.", "name": "s3ScanExcludeRegex", "type": "text", "label": "Exclude Regular Expression", "value": "", "required": false, "defaultValue": ""}, {"info": "Only files created on or after this RFC-3339 UTC timestamp will be discovered.", "name": "s3ScanModStartTimeUTC", "type": "text", "label": "Start Time", "value": "", "required": false, "defaultValue": ""}, {"info": "Only files created before this RFC-3339 UTC timestamp will be discovered.", "name": "s3ScanModEndTimeUTC", "type": "text", "label": "End Time", "value": "", "required": false, "defaultValue": ""}, {"info": "If provided, the adapter will use the configuration in the media source for files to discover instead of scanning the bucket directly.", "name": "scanMediaSourceID", "type": "text", "label": "Media Source ID for Scanning", "value": "", "required": false, "defaultValue": ""}, {"info": "If true, files that were previously ingested will be ignored during discovery. If false, previously ingested files will be marked as updated and may be re-processed. ", "name": "ignoreIngested", "type": "text", "label": "Ignore Previously Ingested Files", "value": "false", "required": false, "defaultValue": "false"}]'::jsonb, 
  false,
  false,
  EXTRACT(EPOCH FROM NOW())::int4,
  EXTRACT(EPOCH FROM NOW())::int4,
  false,
  'https://s3.amazonaws.com/prod-api-2023.veritone.com/7682/other/2026/2/2/_/s3da-v2-14-9-329_f37fd4d4-6ee6-4346-8d44-89b8f85cdc8e.png',
  '{"roles": [{"roleName": "adapter", "taskRights": ["task.update", "task_type.internal", "cms.sources.read", "aiware.slug.read"], "assetRights": ["asset.uri", "asset.all", "recording.read", "recording.update", "recording.create"]}]}'::jsonb,
  '["- Iron Bank hardened deployment available."]'::jsonb,
  '[]'::jsonb,
  '{"engineMode": "batch"}'::jsonb,
  3,
  'public'::job_new.distribution_type
)
ON CONFLICT (engine_id) DO UPDATE SET
  engine_name = EXCLUDED.engine_name,
  engine_description = EXCLUDED.engine_description,
  deployment_model = EXCLUDED.deployment_model,
  is_public = EXCLUDED.is_public,
  fields = EXCLUDED.fields,
  creates_recording = EXCLUDED.creates_recording,
  deleted = EXCLUDED.deleted,
  updated_date = EXCLUDED.updated_date,
  library_required = EXCLUDED.library_required,
  icon_path = EXCLUDED.icon_path,
  jwt_rights = EXCLUDED.jwt_rights,
  engine_manifest = EXCLUDED.engine_manifest,
  edge_version = EXCLUDED.edge_version,
  distribution_type = EXCLUDED.distribution_type
;