-- PODCAST Adapter V3
INSERT INTO job_new.engine(
    "engine_id",
    "engine_category_id",
    "engine_name",
    "engine_description",
    "engine_state",
    "deployment_model",
    "owner_organization_id",
    "is_public",
    "price",
    "rating",
    "website",
    "logo_path",
    "order",
    "dependency",
    "core_job_data",
    "fields",
    "validation",
    "application_id",
    "asset",
    "creates_recording",
    "deleted",
    "created_date",
    "updated_date",
    "library_required",
    "icon_path",
    "engine_currency",
    "engine_alias_id",
    "engine_alias_name",
    "engine_alias_description",
    "engine_alias_logo_path",
    "jwt_rights",
    "use_cases",
    "industries",
    "engine_manifest",
    "edge_version",
    "single_engine_tdo_job_json",
    "single_engine_upload_job_json",
    "cpu_resource_mcpu",
    "cpu_shares",
    "gpu_supported",
    "memory_resource_bytes",
    "storage_resource_bytes",
    "distribution_type",
    "metadata_version"
) VALUES (
    'a725de38-f538-4c4a-b835-b0bd4ab1a255',
    '4b150c85-82d0-4a18-b7fb-63e4a58dfcce',
    'Podcast Adapter',
    'Scans podcasts for import',
    'active',
    1,
    1,
    TRUE,
    NULL,
    NULL,
    NULL,
    'https://www.filepicker.io/api/file/KdCg5PKzQcSOyjOu2tQf',
    200,
    NULL,
    NULL,
    '[]',
    NULL,
    NULL,
    NULL,
    TRUE,
    FALSE,
    1533264371,
    1607937176,
    FALSE,
    NULL,
    'USD',
    'a725de38-f538-4c4a-b835-b0bd4ab1a255',
    'Adapter (Stream): Podcast',
    NULL,
    NULL,
    '{"roles": [{"roleName": "adapter", "taskRights": ["job:create", "job.read", "cms.access", "cms.sources.read", "cms.sources.update", "task_type:internal"], "assetRights": ["recording:create", "recording:update"]}]}',
    NULL,
    NULL,
    '{"engineMode": "stream", "supportedInputTypes": ["application/json"]}',
    3,
    NULL,
    NULL,
    1024,
    1024,
    'none',
    2147483648,
    1073741824,
    'public',
    1
) ON CONFLICT DO NOTHING;

INSERT INTO job_new.build(
    "engine_id",
    "build_id",
    "version",
    "build_state",
    "price",
    "created_date",
    "updated_date",
    "deployment_model",
    "docker_image",
    "task_runtime",
    "is_legacy",
    "vul_low_count",
    "vul_medium_count",
    "vul_high_count",
    "vul_critical_count",
    "build_size",
    "deploy_date",
    "manifest",
    "data_certified",
    "release_notes"
) VALUES (
    'a725de38-f538-4c4a-b835-b0bd4ab1a255',
    'ad249179-f0c2-4fcd-ac91-4b99d897281a',
    6,
    'deployed',
    NULL,
    1604642071,
    1604642071,
    0,
    'registry.central.aiware.com/a725de38-f538-4c4a-b835-b0bd4ab1a255:ad249179-f0c2-4fcd-ac91-4b99d897281a',
    '{"edge": {}}',
    FALSE,
    25,
    12,
    NULL,
    NULL,
    718499801,
    NULL,
    '{"url": "https://github.com/veritone/realtime/master/modules/engines/podcast_adapter", "user": "qdang+superadmin@veritone.com", "build": "ad249179-f0c2-4fcd-ac91-4b99d897281a", "oauth": "", "runtime": "", "category": "ingestion", "engineId": "a725de38-f538-4c4a-b835-b0bd4ab1a255", "isPublic": true, "schedule": "", "schemaId": 0, "sourceId": 0, "ingestion": {"scanner": false, "supportsLiveStreams": false, "supportedSourceTypes": ["4"]}, "libraries": null, "maxFileMb": 0, "categories": null, "engineMode": "stream", "clusterSize": "small", "isBenchmark": false, "isConductor": false, "gpuSupported": "", "inputOptions": null, "releaseNotes": "etversion=.;builddate=2020-11-06_02:49:50;branch=master;commit=1aa15a28351c33fa1b3637eda52375a156333cc9", "customProfile": "", "externalCalls": [], "inputEncoding": "", "outputFormats": ["video/mp4"], "serverCountry": "", "volumeProfile": "", "maxConcurrency": 50, "isCJISCompliant": false, "trainableViaApi": false, "whitelistOrgIds": null, "maxMediaLengthMs": 0, "minMediaLengthMs": 0, "fedRampImpactLevel": 0, "initialConcurrency": 50, "sourceFileDeletion": false, "supportedLanguages": null, "preferredInputFormat": "application/json", "supportedInputFormats": null}',
    NULL,
    NULL
) ON CONFLICT DO NOTHING;
