-- Update "forgot-password" template
UPDATE aiware.email_template
SET code = '
"<!DOCTYPE html><html><head><link href=\"https://fonts.googleapis.com/css?family=Roboto:300,400,500\" rel=\"stylesheet\"></head><body style=\"font-family:&#039;Roboto&#039;,Arial, Helvetica, sans-serif\"><div style=\"max-width:600px; margin:0 auto; min-width:320px; box-shadow: 0 3px 5px -1px rgba(0,0,0,.2),0 5px 8px 0 rgba(0,0,0,.14),0 1px 14px 0 rgba(0,0,0,.12)\">    <div style=\" min-height:60px; padding:40px 20px 0px 40px; \"> <img src=\"https://static.veritone.com/logo/veritone-small-logo-v2.png\" alt=\"Veritone\" style=\"max-height:44px; width:auto\"/></div><div style=\"background-color:#ffffff; padding:40px 40px\"><div style=\"font-size:18px; line-height:24px; color:#777\"><div style=\"font-size: 26px; line-height: 60px; color:#222\">Forgot your password?</div>We heard that you need to reset your password. Please click the button below to be redirected to a secure site where you can create a new one.<div style=\"padding: 20px 0\"><a style=\"font-size: 13px; text-decoration: none; margin: 30px 0; padding: 10px 15px; height: 44px; line-height: 44px; border-radius: 3px; color: white; text-align: center; background-color: #53ac57; text-transform: uppercase; box-shadow: 0 2px 2px 0 rgba(0, 0, 0, 0.24), 0 0 2px 0 rgba(0, 0, 0, 0.12);\" href=\"{{resetPasswordLink}}\">Reset Password</a></div><br>Please note that this link will expire in {{resetExpiryText}}. After that, you’ll need to submit a new password reset request. If you didn’t request a password reset, please contact us.</div></div></div><div style=\"max-width:600px; margin:70px auto; min-width:320px; font-size:12px; color:#777; text-align:center\">© {{year}} Veritone, Inc. All Rights Reserved.  <a href=\"https://www.veritone.com/wp/terms/\" style=\"color: #0288d1; text-decoration:none\">Terms of Use</a>  <a href=\"https://www.veritone.com/wp/privacy/\" style=\"color: #0288d1; text-decoration:none\">Privacy Policy</a></div></body></html>"
'::jsonb,
updated_date = NOW(),
updated_by = '00000000-0000-0000-0000-000000000000'
WHERE email_template_id = 'forgot-password';

-- Update "admin-reset-password" template
UPDATE aiware.email_template
SET code = '
"<!DOCTYPE html><html><head><link href=\"https://fonts.googleapis.com/css?family=Roboto:300,400,500\" rel=\"stylesheet\"></head><body style=\"font-family:&#039;Roboto&#039;,Arial, Helvetica, sans-serif\"><div style=\"max-width:600px; margin:0 auto; min-width:320px;            box-shadow: 0 3px 5px -1px rgba(0,0,0,.2),0 5px 8px 0 rgba(0,0,0,.14),0 1px 14px 0 rgba(0,0,0,.12)\"><div style=\" min-height:60px; padding:40px 20px 0px 40px; \"> <img src=\"https://static.veritone.com/logo/veritone-small-logo-v2.png\" alt=\"Veritone\" style=\"max-height:44px; width:auto\"/></div><div style=\"background-color:#ffffff; padding:40px 40px\"><div style=\"font-size:18px; line-height:24px; color:#777\"><div style=\"font-size: 26px; line-height: 60px; color:#222\">Please Change Your Password</div>An administrator for your organization has requested that you change your account password. Please click the button below to do so.<div style=\"padding: 20px 0\"><a style=\"font-size: 13px; text-decoration: none; margin: 30px 0; padding: 10px 15px; height: 44px; line-height: 44px; border-radius: 3px; color: white; text-align: center; background-color: #53ac57; text-transform: uppercase; box-shadow: 0 2px 2px 0 rgba(0, 0, 0, 0.24), 0 0 2px 0 rgba(0, 0, 0, 0.12);\" href=\"{{resetPasswordLink}}\">Change Password</a></div>Or change your password using this link:<br><a href=\"{{resetPasswordLink}}\" style=\"color: #0288d1; text-decoration: none\">{{resetPasswordLink}}</a><br><br><br>Alternatively, the next time you log into your account you will be asked to change your password.<br><br>Please note that this link will expire after {{resetExpiryText}}.</div></div></div><div style=\"max-width:600px; margin:70px auto; min-width:320px; font-size:12px; color:#777; text-align:center\">© {{year}} Veritone, Inc. All Rights Reserved.  <a href=\"https://www.veritone.com/wp/terms/\" style=\"color: #0288d1; text-decoration:none\">Terms of Use</a>  <a href=\"https://www.veritone.com/wp/privacy/\" style=\"color: #0288d1; text-decoration:none\">Privacy Policy</a></div></body></html>"
'::jsonb,
updated_date = NOW(),
updated_by = '00000000-0000-0000-0000-000000000000'
WHERE email_template_id = 'admin-reset-password';
