ALTER TABLE flows ADD COLUMN IF NOT EXISTS created_date_time TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE flows ADD COLUMN IF NOT EXISTS modified_date_time TIMESTAMP WITH TIME ZONE;
ALTER TABLE flows ADD COLUMN IF NOT EXISTS package VARCHAR;
