INSERT INTO "job_new"."engine_category"(
	engine_category_id,
	engine_category_name,
	engine_category_description,
	"search",
	elastic,
	data_field,
	icon_class,
	editable,
	video_only,
	"order",
	library_identifier_types,
	dependencies,
	color,
	engine_class_id,
	engine_type_id,
	export_formats,
	validation_contract,
	doc_link
) values (
	'078d34a7-80b4-4efe-903f-2f13392deca8',
	'Generator',
	'Generate entities for cognitive training and processing purposes',
	NULL,
	NULL,
	NULL,
	'icon-pull',
	FALSE,
	FALSE,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	'0ab2745b-ca6b-43c9-befd-0ef1d28cb96d',
	'[]',
	NULL,
	null
) ON CONFLICT DO NOTHING;
