INSERT INTO "job_new"."engine_category"(
	engine_category_id,
	engine_category_name,
	engine_category_description,
	"search",
	elastic,
	data_field,
	icon_class,
	editable,
	video_only,
	"order",
	library_identifier_types,
	dependencies,
	color,
	engine_class_id,
	engine_type_id,
	export_formats,
	validation_contract,
	doc_link
) values (
	'd110089c-9a95-4dee-8411-b79472a0be50',
	'Alteryx',
	'Automate Flows and Engines used for Alteryx Integration',
	NULL,
	NULL,
	NULL,
	NULL,
	FALSE,
	FALSE,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	'fcc22feb-9184-4f53-be5e-7694927864d9',
	'[]',
	NULL,
	null
) ON CONFLICT DO NOTHING;
