-- Engine 9e611ad7-2d3b-48f6-a51b-0a1ba40fe255 with deployed build 7444d4b7-7cd1-46a8-b751-0550c9619a9f:
INSERT INTO job_new.engine
  (
    "engine_id",
    "engine_category_id",
    "engine_name",
    "engine_description",
    "engine_state",
    "deployment_model",
    "owner_organization_id",
    "is_public",
    "price",
    "rating",
    "website",
    "logo_path",
    "order",
    "dependency",
    "core_job_data",
    "fields",
    "validation",
    "application_id",
    "asset",
    "creates_recording",
    "deleted",
    "created_date",
    "updated_date",
    "library_required",
    "icon_path",
    "engine_currency",
    "engine_alias_id",
    "engine_alias_name",
    "engine_alias_description",
    "engine_alias_logo_path",
    "jwt_rights",
    "use_cases",
    "industries",
    "engine_manifest",
    "edge_version",
    "single_engine_tdo_job_json",
    "single_engine_upload_job_json"
  )
VALUES
  (
    '9e611ad7-2d3b-48f6-a51b-0a1ba40fe255',
    '4b150c85-82d0-4a18-b7fb-63e4a58dfcce',
    'Webstream Adapter V3F',
    'Real-time adapter for ingesting web streams from a URL',
    'active',
    1,
    7682,
    TRUE,
    NULL,
    NULL,
    NULL,
    'https://www.filepicker.io/api/file/QFdep7moSTetadeYF3E7',
    200,
    NULL,
    NULL,
    '[]',
    NULL,
    NULL,
    NULL,
    TRUE,
    FALSE,
    1521659424,
    1607937176,
    FALSE,
    NULL,
    'USD',
    '9e611ad7-2d3b-48f6-a51b-0a1ba40fe255',
    'Webstream Adapter V3F',
    NULL,
    NULL,
    '{"roles": [{"roleName": "adapter", "taskRights": ["job:create", "cms.access", "cms.sources.read", "cms.sources.update"], "assetRights": ["recording:create", "recording:update"]}]}',
    NULL,
    NULL,
    NULL,
    3,
    NULL,
    NULL
  )
ON CONFLICT ("engine_id") DO NOTHING;

UPDATE job_new.build SET build_state = 'paused'
  WHERE engine_id = '9e611ad7-2d3b-48f6-a51b-0a1ba40fe255' AND build_id != '7444d4b7-7cd1-46a8-b751-0550c9619a9f' AND build_state = 'deployed';

INSERT INTO job_new.build
  (
    "engine_id",
    "build_id",
    "version",
    "build_state",
    "price",
    "created_date",
    "updated_date",
    "deployment_model",
    "docker_image",
    "task_runtime",
    "is_legacy",
    "vul_low_count",
    "vul_medium_count",
    "vul_high_count",
    "vul_critical_count",
    "build_size",
    "deploy_date",
    "manifest",
    "data_certified"
  )
VALUES
  (
    '9e611ad7-2d3b-48f6-a51b-0a1ba40fe255',
    '7444d4b7-7cd1-46a8-b751-0550c9619a9f',
    20,
    'deployed',
    NULL,
    1604631362,
    1604631362,
    0,
    'registry.central.aiware.com/9e611ad7-2d3b-48f6-a51b-0a1ba40fe255:7444d4b7-7cd1-46a8-b751-0550c9619a9f',
    '{"edge": {}}',
    FALSE,
    25,
    12,
    NULL,
    NULL,
    718499903,
    NULL,
    '{"url": "https://github.com/veritone/realtime/tree/master/modules/engines/wsa_tvr_adapter", "user": "qdang+superadmin@veritone.com", "build": "7444d4b7-7cd1-46a8-b751-0550c9619a9f", "oauth": "", "runtime": "", "category": "ingestion", "engineId": "9e611ad7-2d3b-48f6-a51b-0a1ba40fe255", "isPublic": true, "schedule": "recurring", "schemaId": 0, "sourceId": 0, "ingestion": {"scanner": false, "supportsLiveStreams": false, "supportedSourceTypes": ["6"]}, "libraries": null, "maxFileMb": 0, "categories": null, "engineMode": "stream", "clusterSize": "custom", "isBenchmark": false, "isConductor": false, "gpuSupported": "", "inputOptions": null, "releaseNotes": "etversion=.;builddate=2020-11-06_02:49:40;branch=master;commit=1aa15a28351c33fa1b3637eda52375a156333cc9", "customProfile": "webstream-adapter", "externalCalls": [], "inputEncoding": "", "outputFormats": ["video/webm"], "serverCountry": "", "volumeProfile": "", "maxConcurrency": 50, "isCJISCompliant": false, "trainableViaApi": false, "whitelistOrgIds": null, "maxMediaLengthMs": 0, "minMediaLengthMs": 0, "fedRampImpactLevel": 0, "initialConcurrency": 50, "sourceFileDeletion": false, "supportedLanguages": null, "preferredInputFormat": "application/json", "supportedInputFormats": null}',
    NULL
  )
ON CONFLICT ("build_id") DO NOTHING;




-- Engine 74dfd76b-472a-48f0-8395-c7e01dd7f255 with deployed build 32b0188d-e7e0-4c6e-a8f3-435d83cafa1d:
INSERT INTO job_new.engine
  (
    "engine_id",
    "engine_category_id",
    "engine_name",
    "engine_description",
    "engine_state",
    "deployment_model",
    "owner_organization_id",
    "is_public",
    "price",
    "rating",
    "website",
    "logo_path",
    "order",
    "dependency",
    "core_job_data",
    "fields",
    "validation",
    "application_id",
    "asset",
    "creates_recording",
    "deleted",
    "created_date",
    "updated_date",
    "library_required",
    "icon_path",
    "engine_currency",
    "engine_alias_id",
    "engine_alias_name",
    "engine_alias_description",
    "engine_alias_logo_path",
    "jwt_rights",
    "use_cases",
    "industries",
    "engine_manifest",
    "edge_version",
    "single_engine_tdo_job_json",
    "single_engine_upload_job_json"
  )
VALUES
  (
    '74dfd76b-472a-48f0-8395-c7e01dd7f255',
    '4b150c85-82d0-4a18-b7fb-63e4a58dfcce',
    'TV and Radio Adapter V3F',
    'Pulls data from TV and Radio streams.',
    'active',
    1,
    7682,
    TRUE,
    NULL,
    NULL,
    NULL,
    'https://www.filepicker.io/api/file/MSOOWq06TnmWq5TyncOQ',
    200,
    NULL,
    NULL,
    '[]',
    NULL,
    NULL,
    NULL,
    TRUE,
    FALSE,
    1533254106,
    1607937176,
    FALSE,
    NULL,
    'USD',
    '74dfd76b-472a-48f0-8395-c7e01dd7f255',
    NULL,
    NULL,
    NULL,
    '{"roles": [{"roleName": "adapter", "taskRights": ["job:create", "cms.access", "cms.sources.read", "cms.sources.update"], "assetRights": ["recording:create", "recording:update"]}]}',
    NULL,
    NULL,
    NULL,
    3,
    NULL,
    NULL
  )
ON CONFLICT ("engine_id") DO NOTHING;

UPDATE job_new.build SET build_state = 'paused'
  WHERE engine_id = '74dfd76b-472a-48f0-8395-c7e01dd7f255' AND build_id != '32b0188d-e7e0-4c6e-a8f3-435d83cafa1d' AND build_state = 'deployed';

INSERT INTO job_new.build
  (
    "engine_id",
    "build_id",
    "version",
    "build_state",
    "price",
    "created_date",
    "updated_date",
    "deployment_model",
    "docker_image",
    "task_runtime",
    "is_legacy",
    "vul_low_count",
    "vul_medium_count",
    "vul_high_count",
    "vul_critical_count",
    "build_size",
    "deploy_date",
    "manifest",
    "data_certified"
  )
VALUES
  (
    '74dfd76b-472a-48f0-8395-c7e01dd7f255',
    '32b0188d-e7e0-4c6e-a8f3-435d83cafa1d',
    19,
    'deployed',
    NULL,
    1604631374,
    1604631374,
    0,
    'registry.central.aiware.com/74dfd76b-472a-48f0-8395-c7e01dd7f255:32b0188d-e7e0-4c6e-a8f3-435d83cafa1d',
    '{"edge": {}}',
    FALSE,
    25,
    12,
    NULL,
    NULL,
    718499918,
    NULL,
    '{"url": "https://github.com/veritone/realtime/tree/master/modules/engines/wsa_tvr_adapter", "user": "qdang+superadmin@veritone.com", "build": "32b0188d-e7e0-4c6e-a8f3-435d83cafa1d", "oauth": "", "runtime": "", "category": "ingestion", "engineId": "74dfd76b-472a-48f0-8395-c7e01dd7f255", "isPublic": true, "schedule": "recurring", "schemaId": 0, "sourceId": 0, "ingestion": {"scanner": false, "supportsLiveStreams": false, "supportedSourceTypes": ["1", "2"]}, "libraries": null, "maxFileMb": 0, "categories": null, "engineMode": "stream", "clusterSize": "custom", "isBenchmark": false, "isConductor": false, "gpuSupported": "", "inputOptions": null, "releaseNotes": "etversion=.;builddate=2020-11-06_02:49:45;branch=master;commit=1aa15a28351c33fa1b3637eda52375a156333cc9", "customProfile": "webstream-adapter", "externalCalls": [], "inputEncoding": "", "outputFormats": ["video/webm"], "serverCountry": "", "volumeProfile": "", "maxConcurrency": 50, "isCJISCompliant": false, "trainableViaApi": false, "whitelistOrgIds": null, "maxMediaLengthMs": 0, "minMediaLengthMs": 0, "fedRampImpactLevel": 0, "initialConcurrency": 50, "sourceFileDeletion": false, "supportedLanguages": null, "preferredInputFormat": "application/json", "supportedInputFormats": null}',
    NULL
  )
ON CONFLICT ("build_id") DO NOTHING;




-- Engine 8bdb0e3b-ff28-4f6e-a3ba-887bd06e6440 with deployed build 69baf48d-b9ac-4d26-a121-4dd17182c222:
INSERT INTO job_new.engine
  (
    "engine_id",
    "engine_category_id",
    "engine_name",
    "engine_description",
    "engine_state",
    "deployment_model",
    "owner_organization_id",
    "is_public",
    "price",
    "rating",
    "website",
    "logo_path",
    "order",
    "dependency",
    "core_job_data",
    "fields",
    "validation",
    "application_id",
    "asset",
    "creates_recording",
    "deleted",
    "created_date",
    "updated_date",
    "library_required",
    "icon_path",
    "engine_currency",
    "engine_alias_id",
    "engine_alias_name",
    "engine_alias_description",
    "engine_alias_logo_path",
    "jwt_rights",
    "use_cases",
    "industries",
    "engine_manifest",
    "edge_version",
    "single_engine_tdo_job_json",
    "single_engine_upload_job_json"
  )
VALUES
  (
    '8bdb0e3b-ff28-4f6e-a3ba-887bd06e6440',
    '4be1a1b2-653d-4eaa-ba18-747a265305d8',
    'SI2 audio/video Chunk creator V3F',
    'Engine used for splitting a stream to audio or video',
    'active',
    0,
    7682,
    TRUE,
    NULL,
    NULL,
    NULL,
    'https://www.filepicker.io/api/file/p2bLdy4nRrOwv34yoEhg',
    200,
    NULL,
    NULL,
    '[]',
    NULL,
    NULL,
    NULL,
    TRUE,
    FALSE,
    1571251687,
    1607937176,
    FALSE,
    NULL,
    'USD',
    '8bdb0e3b-ff28-4f6e-a3ba-887bd06e6440',
    'SI2 audio/video Chunk creator',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    3,
    NULL,
    NULL
  )
ON CONFLICT ("engine_id") DO NOTHING;

UPDATE job_new.build SET build_state = 'paused'
  WHERE engine_id = '8bdb0e3b-ff28-4f6e-a3ba-887bd06e6440' AND build_id != '69baf48d-b9ac-4d26-a121-4dd17182c222' AND build_state = 'deployed';

INSERT INTO job_new.build
  (
    "engine_id",
    "build_id",
    "version",
    "build_state",
    "price",
    "created_date",
    "updated_date",
    "deployment_model",
    "docker_image",
    "task_runtime",
    "is_legacy",
    "vul_low_count",
    "vul_medium_count",
    "vul_high_count",
    "vul_critical_count",
    "build_size",
    "deploy_date",
    "manifest",
    "data_certified"
  )
VALUES
  (
    '8bdb0e3b-ff28-4f6e-a3ba-887bd06e6440',
    '69baf48d-b9ac-4d26-a121-4dd17182c222',
    19,
    'deployed',
    NULL,
    1604639663,
    1604639663,
    0,
    'registry.central.aiware.com/8bdb0e3b-ff28-4f6e-a3ba-887bd06e6440:69baf48d-b9ac-4d26-a121-4dd17182c222',
    '{"edge": {}}',
    FALSE,
    25,
    12,
    NULL,
    NULL,
    718499645,
    NULL,
    '{"url": "https://github.com/veritone/realtime/tree/master/modules/engines/siv2ffmpeg", "user": "qdang+superadmin@veritone.com", "build": "69baf48d-b9ac-4d26-a121-4dd17182c222", "oauth": "", "runtime": "", "category": "ingestion", "engineId": "8bdb0e3b-ff28-4f6e-a3ba-887bd06e6440", "isPublic": true, "schedule": "", "schemaId": 0, "sourceId": 0, "ingestion": {"scanner": false, "supportsLiveStreams": false, "supportedSourceTypes": null}, "libraries": null, "maxFileMb": 0, "categories": null, "engineMode": "stream", "clusterSize": "custom", "isBenchmark": false, "isConductor": false, "gpuSupported": "", "inputOptions": null, "releaseNotes": "etversion=.;builddate=2020-11-06_02:50:14;branch=master;commit=1aa15a28351c33fa1b3637eda52375a156333cc9", "customProfile": "stream-ingestor", "externalCalls": [], "inputEncoding": "", "outputFormats": ["video/mp4"], "serverCountry": "", "volumeProfile": "", "maxConcurrency": 50, "isCJISCompliant": false, "trainableViaApi": false, "whitelistOrgIds": null, "maxMediaLengthMs": 0, "minMediaLengthMs": 0, "fedRampImpactLevel": 0, "initialConcurrency": 50, "sourceFileDeletion": false, "supportedLanguages": null, "preferredInputFormat": "application/json", "supportedInputFormats": null}',
    NULL
  )
ON CONFLICT ("build_id") DO NOTHING;




-- Engine 352556c7-de07-4d55-b33f-74b1cf237f25 with deployed build 4164bdaf-b483-4a9c-b2d1-644457919574:
INSERT INTO job_new.engine
  (
    "engine_id",
    "engine_category_id",
    "engine_name",
    "engine_description",
    "engine_state",
    "deployment_model",
    "owner_organization_id",
    "is_public",
    "price",
    "rating",
    "website",
    "logo_path",
    "order",
    "dependency",
    "core_job_data",
    "fields",
    "validation",
    "application_id",
    "asset",
    "creates_recording",
    "deleted",
    "created_date",
    "updated_date",
    "library_required",
    "icon_path",
    "engine_currency",
    "engine_alias_id",
    "engine_alias_name",
    "engine_alias_description",
    "engine_alias_logo_path",
    "jwt_rights",
    "use_cases",
    "industries",
    "engine_manifest",
    "edge_version",
    "single_engine_tdo_job_json",
    "single_engine_upload_job_json"
  )
VALUES
  (
    '352556c7-de07-4d55-b33f-74b1cf237f25',
    '4be1a1b2-653d-4eaa-ba18-747a265305d8',
    'SI2 Playback segment creator V3F',
    'Engine used for creating playback segments from an input stream into the TDO.  Should be for initial ingestion only',
    'active',
    0,
    7682,
    TRUE,
    NULL,
    NULL,
    NULL,
    'https://www.filepicker.io/api/file/p2bLdy4nRrOwv34yoEhg',
    200,
    NULL,
    NULL,
    '[]',
    NULL,
    NULL,
    NULL,
    TRUE,
    FALSE,
    1571251687,
    1607937176,
    FALSE,
    NULL,
    'USD',
    '352556c7-de07-4d55-b33f-74b1cf237f25',
    'SI2 Playback segment creator',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    3,
    NULL,
    NULL
  )
ON CONFLICT ("engine_id") DO NOTHING;

UPDATE job_new.build SET build_state = 'paused'
  WHERE engine_id = '352556c7-de07-4d55-b33f-74b1cf237f25' AND build_id != '4164bdaf-b483-4a9c-b2d1-644457919574' AND build_state = 'deployed';

INSERT INTO job_new.build
  (
    "engine_id",
    "build_id",
    "version",
    "build_state",
    "price",
    "created_date",
    "updated_date",
    "deployment_model",
    "docker_image",
    "task_runtime",
    "is_legacy",
    "vul_low_count",
    "vul_medium_count",
    "vul_high_count",
    "vul_critical_count",
    "build_size",
    "deploy_date",
    "manifest",
    "data_certified"
  )
VALUES
  (
    '352556c7-de07-4d55-b33f-74b1cf237f25',
    '4164bdaf-b483-4a9c-b2d1-644457919574',
    18,
    'deployed',
    NULL,
    1604631474,
    1604631474,
    0,
    'registry.central.aiware.com/352556c7-de07-4d55-b33f-74b1cf237f25:4164bdaf-b483-4a9c-b2d1-644457919574',
    '{"edge": {}}',
    FALSE,
    25,
    12,
    NULL,
    NULL,
    718499651,
    NULL,
    '{"url": "https://github.com/veritone/realtime/tree/master/modules/engines/siv2playback", "user": "qdang+superadmin@veritone.com", "build": "4164bdaf-b483-4a9c-b2d1-644457919574", "oauth": "", "runtime": "", "category": "ingestion", "engineId": "352556c7-de07-4d55-b33f-74b1cf237f25", "isPublic": true, "schedule": "", "schemaId": 0, "sourceId": 0, "ingestion": {"scanner": false, "supportsLiveStreams": false, "supportedSourceTypes": null}, "libraries": null, "maxFileMb": 0, "categories": null, "engineMode": "stream", "clusterSize": "custom", "isBenchmark": false, "isConductor": false, "gpuSupported": "", "inputOptions": null, "releaseNotes": "etversion=.;builddate=2020-11-06_02:50:05;branch=master;commit=1aa15a28351c33fa1b3637eda52375a156333cc9", "customProfile": "stream-ingestor", "externalCalls": [], "inputEncoding": "", "outputFormats": ["video/mp4"], "serverCountry": "", "volumeProfile": "", "maxConcurrency": 50, "isCJISCompliant": false, "trainableViaApi": false, "whitelistOrgIds": null, "maxMediaLengthMs": 0, "minMediaLengthMs": 0, "fedRampImpactLevel": 0, "initialConcurrency": 50, "sourceFileDeletion": false, "supportedLanguages": null, "preferredInputFormat": "application/json", "supportedInputFormats": null}',
    NULL
  )
ON CONFLICT ("build_id") DO NOTHING;




-- Engine 75fc943b-b5b0-4fe1-bcb6-9a7e1884257a with deployed build 8542d507-be9b-4f4d-946f-9e161c2bec33:
INSERT INTO job_new.engine
  (
    "engine_id",
    "engine_category_id",
    "engine_name",
    "engine_description",
    "engine_state",
    "deployment_model",
    "owner_organization_id",
    "is_public",
    "price",
    "rating",
    "website",
    "logo_path",
    "order",
    "dependency",
    "core_job_data",
    "fields",
    "validation",
    "application_id",
    "asset",
    "creates_recording",
    "deleted",
    "created_date",
    "updated_date",
    "library_required",
    "icon_path",
    "engine_currency",
    "engine_alias_id",
    "engine_alias_name",
    "engine_alias_description",
    "engine_alias_logo_path",
    "jwt_rights",
    "use_cases",
    "industries",
    "engine_manifest",
    "edge_version",
    "single_engine_tdo_job_json",
    "single_engine_upload_job_json"
  )
VALUES
  (
    '75fc943b-b5b0-4fe1-bcb6-9a7e1884257a',
    '4be1a1b2-653d-4eaa-ba18-747a265305d8',
    'SI2 Stream Asset Creator V3F',
    'Engine used for ingesting a stream and storing the data as an asset in the TDO with the given assetType',
    'active',
    0,
    7682,
    TRUE,
    NULL,
    NULL,
    NULL,
    'https://www.filepicker.io/api/file/p2bLdy4nRrOwv34yoEhg',
    200,
    NULL,
    NULL,
    '[]',
    NULL,
    NULL,
    NULL,
    TRUE,
    FALSE,
    1571251687,
    1607937176,
    FALSE,
    NULL,
    'USD',
    '75fc943b-b5b0-4fe1-bcb6-9a7e1884257a',
    'SI2 Stream Asset Creator',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    3,
    NULL,
    NULL
  )
ON CONFLICT ("engine_id") DO NOTHING;

UPDATE job_new.build SET build_state = 'paused'
  WHERE engine_id = '75fc943b-b5b0-4fe1-bcb6-9a7e1884257a' AND build_id != '8542d507-be9b-4f4d-946f-9e161c2bec33' AND build_state = 'deployed';

INSERT INTO job_new.build
  (
    "engine_id",
    "build_id",
    "version",
    "build_state",
    "price",
    "created_date",
    "updated_date",
    "deployment_model",
    "docker_image",
    "task_runtime",
    "is_legacy",
    "vul_low_count",
    "vul_medium_count",
    "vul_high_count",
    "vul_critical_count",
    "build_size",
    "deploy_date",
    "manifest",
    "data_certified"
  )
VALUES
  (
    '75fc943b-b5b0-4fe1-bcb6-9a7e1884257a',
    '8542d507-be9b-4f4d-946f-9e161c2bec33',
    21,
    'deployed',
    NULL,
    1604631533,
    1604631533,
    0,
    'registry.central.aiware.com/75fc943b-b5b0-4fe1-bcb6-9a7e1884257a:8542d507-be9b-4f4d-946f-9e161c2bec33',
    '{"edge": {}}',
    FALSE,
    25,
    12,
    NULL,
    NULL,
    718499639,
    NULL,
    '{"url": "https://github.com/veritone/realtime/tree/master/modules/engines/siv2core", "user": "qdang+superadmin@veritone.com", "build": "8542d507-be9b-4f4d-946f-9e161c2bec33", "oauth": "", "runtime": "", "category": "ingestion", "engineId": "75fc943b-b5b0-4fe1-bcb6-9a7e1884257a", "isPublic": true, "schedule": "", "schemaId": 0, "sourceId": 0, "ingestion": {"scanner": false, "supportsLiveStreams": false, "supportedSourceTypes": null}, "libraries": null, "maxFileMb": 0, "categories": null, "engineMode": "stream", "clusterSize": "custom", "isBenchmark": false, "isConductor": false, "gpuSupported": "", "inputOptions": null, "releaseNotes": "etversion=.;builddate=2020-11-06_02:50:09;branch=master;commit=1aa15a28351c33fa1b3637eda52375a156333cc9", "customProfile": "stream-ingestor", "externalCalls": [], "inputEncoding": "", "outputFormats": ["video/mp4"], "serverCountry": "", "volumeProfile": "", "maxConcurrency": 50, "isCJISCompliant": false, "trainableViaApi": false, "whitelistOrgIds": null, "maxMediaLengthMs": 0, "minMediaLengthMs": 0, "fedRampImpactLevel": 0, "initialConcurrency": 50, "sourceFileDeletion": false, "supportedLanguages": null, "preferredInputFormat": "application/json", "supportedInputFormats": null}',
    NULL
  )
ON CONFLICT ("build_id") DO NOTHING;




-- Engine 8eccf9cc-6b6d-4d7d-8cb3-7ebf4950c5f3 with deployed build 6a5e9035-b51c-406b-9145-f48efb83c006:
INSERT INTO job_new.engine
  (
    "engine_id",
    "engine_category_id",
    "engine_name",
    "engine_description",
    "engine_state",
    "deployment_model",
    "owner_organization_id",
    "is_public",
    "price",
    "rating",
    "website",
    "logo_path",
    "order",
    "dependency",
    "core_job_data",
    "fields",
    "validation",
    "application_id",
    "asset",
    "creates_recording",
    "deleted",
    "created_date",
    "updated_date",
    "library_required",
    "icon_path",
    "engine_currency",
    "engine_alias_id",
    "engine_alias_name",
    "engine_alias_description",
    "engine_alias_logo_path",
    "jwt_rights",
    "use_cases",
    "industries",
    "engine_manifest",
    "edge_version",
    "single_engine_tdo_job_json",
    "single_engine_upload_job_json"
  )
VALUES
  (
    '8eccf9cc-6b6d-4d7d-8cb3-7ebf4950c5f3',
    '925e8039-5246-4ced-9f2b-b456d0b57ea1',
    'Output Writer',
    'Engine used to aggregate engine outputs and produce a final output',
    'active',
    0,
    7682,
    TRUE,
    NULL,
    NULL,
    NULL,
    'https://www.filepicker.io/api/file/p2bLdy4nRrOwv34yoEhg',
    200,
    NULL,
    NULL,
    '[]',
    NULL,
    NULL,
    NULL,
    TRUE,
    FALSE,
    1528493221,
    1607937176,
    FALSE,
    NULL,
    'USD',
    '8eccf9cc-6b6d-4d7d-8cb3-7ebf4950c5f3',
    'Output Writer',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    3,
    NULL,
    NULL
  )
ON CONFLICT ("engine_id") DO NOTHING;

UPDATE job_new.build SET build_state = 'paused'
  WHERE engine_id = '8eccf9cc-6b6d-4d7d-8cb3-7ebf4950c5f3' AND build_id != '6a5e9035-b51c-406b-9145-f48efb83c006' AND build_state = 'deployed';

INSERT INTO job_new.build
  (
    "engine_id",
    "build_id",
    "version",
    "build_state",
    "price",
    "created_date",
    "updated_date",
    "deployment_model",
    "docker_image",
    "task_runtime",
    "is_legacy",
    "vul_low_count",
    "vul_medium_count",
    "vul_high_count",
    "vul_critical_count",
    "build_size",
    "deploy_date",
    "manifest",
    "data_certified"
  )
VALUES
  (
    '8eccf9cc-6b6d-4d7d-8cb3-7ebf4950c5f3',
    '6a5e9035-b51c-406b-9145-f48efb83c006',
    19,
    'deployed',
    NULL,
    1604631941,
    1604631941,
    0,
    'registry.central.aiware.com/8eccf9cc-6b6d-4d7d-8cb3-7ebf4950c5f3:6a5e9035-b51c-406b-9145-f48efb83c006',
    '{"edge": {}}',
    FALSE,
    25,
    12,
    NULL,
    NULL,
    718499570,
    NULL,
    '{"url": "https://github.com/veritone/realtime/tree/master/modules/engines/outputWriter", "user": "qdang+superadmin@veritone.com", "build": "6a5e9035-b51c-406b-9145-f48efb83c006", "oauth": "", "runtime": "", "category": "intra-category", "engineId": "8eccf9cc-6b6d-4d7d-8cb3-7ebf4950c5f3", "isPublic": true, "schedule": "", "schemaId": 0, "sourceId": 0, "ingestion": {"scanner": false, "supportsLiveStreams": false, "supportedSourceTypes": null}, "libraries": null, "maxFileMb": 0, "categories": null, "engineMode": "chunk", "clusterSize": "small", "isBenchmark": false, "isConductor": false, "gpuSupported": "", "inputOptions": null, "releaseNotes": "etversion=.;builddate=2020-11-06_02:50:18;branch=master;commit=1aa15a28351c33fa1b3637eda52375a156333cc9", "customProfile": "", "externalCalls": [], "inputEncoding": "", "outputFormats": ["application/json"], "serverCountry": "", "volumeProfile": "", "maxConcurrency": 50, "isCJISCompliant": false, "trainableViaApi": false, "whitelistOrgIds": null, "maxMediaLengthMs": 0, "minMediaLengthMs": 0, "fedRampImpactLevel": 0, "initialConcurrency": 50, "sourceFileDeletion": false, "supportedLanguages": null, "preferredInputFormat": "application/json", "supportedInputFormats": null}',
    NULL
  )
ON CONFLICT ("build_id") DO NOTHING;




-- Engine c0e55cde-340b-44d7-bb42-2e0d65e98255 with deployed build 7b6b8ea3-c0cd-4ae2-8857-64cdad787da4:
INSERT INTO job_new.engine
  (
    "engine_id",
    "engine_category_id",
    "engine_name",
    "engine_description",
    "engine_state",
    "deployment_model",
    "owner_organization_id",
    "is_public",
    "price",
    "rating",
    "website",
    "logo_path",
    "order",
    "dependency",
    "core_job_data",
    "fields",
    "validation",
    "application_id",
    "asset",
    "creates_recording",
    "deleted",
    "created_date",
    "updated_date",
    "library_required",
    "icon_path",
    "engine_currency",
    "engine_alias_id",
    "engine_alias_name",
    "engine_alias_description",
    "engine_alias_logo_path",
    "jwt_rights",
    "use_cases",
    "industries",
    "engine_manifest",
    "edge_version",
    "single_engine_tdo_job_json",
    "single_engine_upload_job_json"
  )
VALUES
  (
    'c0e55cde-340b-44d7-bb42-2e0d65e98255',
    '67cd4dd0-2f75-445d-a6f0-2f297d6cd182',
    'Speechmatics Transcription (v7) - English (Global) V3',
    'This engine converts US English speech to text.',
    'active',
    0,
    7682,
    TRUE,
    125,
    NULL,
    NULL,
    NULL,
    112,
    NULL,
    '{"category": "transcribe", "dependencies": ["ingestion", "transcode"]}',
    '[{"max": null, "min": null, "info": "Allows a custom dictionary wordlist to be added to the engine at runtime. Having additional words can improve the likelihood they will be output in the final transcription. Words and phrases must be comma-delimited.", "name": "keywords", "step": null, "type": "text", "label": "keywords", "value": null, "options": null, "required": null, "defaultValue": null}, {"max": null, "min": null, "info": "Type of speaker recognition to include in the output: none - transcription only, no dirization; speaker - speaker identification, takes significantly longer; speaker_change - speaker changed, but no identification", "name": "diarization", "step": null, "type": "picklist", "label": "diarization", "value": null, "options": [{"key": "none", "value": "none"}, {"key": "speaker", "value": "speaker"}, {"key": "speaker_change", "value": "speaker_change"}], "required": false, "defaultValue": null}, {"max": null, "min": null, "info": "How sensitive to speaker changes the algorithm should be. Only used if diarization = speaker_change. Value must be a number in the range of 0.0 to 1.0, higher numbers are more sensitive (more frequent changes detected).", "name": "speakerChangeSensitivity", "step": null, "type": "text", "label": "speakerChangeSensitivity", "value": "0.4", "options": null, "required": false, "defaultValue": "0.4"}, {"max": null, "min": null, "info": "Include punctuation in the output", "name": "advancedPunctuation", "step": null, "type": "picklist", "label": "advancedPunctuation", "value": "true", "options": [{"key": "enabled", "value": "true"}, {"key": "disabled", "value": "false"}], "required": false, "defaultValue": "true"}]',
    NULL,
    NULL,
    'c0e55cde-340b-44d7-bb42-2e0d65e98255',
    FALSE,
    FALSE,
    1522199471,
    1611721114,
    FALSE,
    'https://www.filepicker.io/api/file/PYhnibSPSYGNLF2xFzGV',
    'USD',
    'c0e55cde-340b-44d7-bb42-2e0d65e98255',
    'Transcription - E - English (Global) V3',
    'This engine converts US English speech to text.',
    NULL,
    NULL,
    NULL,
    NULL,
    '{"engineMode": "chunk", "supportedInputTypes": ["text/html"]}',
    3,
    '{"template": "{\n  \"targetId\":{{#if TARGET_ID}} \"{{{TARGET_ID}}}\" {{else}} \"{{{TDO_ID}}}\" {{/if}},\n  {{#if notificationUri}} \"notificationUris\":[\"{{{notificationUri}}}\"], {{/if}}\n  {{#if clusterId}} \"clusterId\":\"{{{clusterId}}}\", {{/if}}\n  \"tasks\":[\n    {\n      \"engineId\":\"9e611ad7-2d3b-48f6-a51b-0a1ba40fe255\",\n      \"payload\":{\n        \"url\":\"{{{UPLOAD_URL}}}\"\n      },\n      \"executionPreferences\":{\n         \"priority\":{{#if priority}} {{{priority}}} {{else}} \"-20\" {{/if}}\n      },\n      \"ioFolders\":[\n        {\n          \"referenceId\":\"wsa-output\",\n          \"mode\":\"stream\",\n          \"type\":\"output\"\n        }\n      ]\n    },\n    {\n      \"engineId\":\"8bdb0e3b-ff28-4f6e-a3ba-887bd06e6440\",\n      \"payload\":{\n        \"ffmpegTemplate\":\"audio\",\n        \"customFFMPEGProperties\":{\n          \"chunkSizeInSeconds\":{{#if chunkSizeInSeconds}} \"{{{chunkSizeInSeconds}}}\" {{else}} \"300\" {{/if}}\n        }\n      },\n      \"executionPreferences\":{\n        \"priority\":{{#if priority}} {{{priority}}} {{else}} \"-20\", {{/if}}\n        \"parentCompleteBeforeStarting\":true\n      },\n      \"ioFolders\":[\n        {\n          \"referenceId\":\"si-input\",\n          \"mode\":\"stream\",\n          \"type\":\"input\"\n        },\n        {\n          \"referenceId\":\"si-output\",\n          \"mode\":\"chunk\",\n          \"type\":\"output\"\n        }\n      ]\n    },\n    {\n      \"engineId\":\"{{{ENGINE_ID}}}\",\n      \"payload\":{\n        {{#if diarise}} \"diarise\":\"{{{diarise}}}\", {{/if}}\n        {{#if keywords}} \"keywords\":\"{{{keywords}}}\", {{/if}}\n        \"COMMA_CATCHER\":\"true\"\n      },\n      \"executionPreferences\":{\n        \"priority\":{{#if priority}} {{{priority}}} {{else}} \"-20\", {{/if}}\n        \"parentCompleteBeforeStarting\":true\n      },\n      \"ioFolders\":[\n        {\n          \"referenceId\":\"engine-input\",\n          \"mode\":\"chunk\",\n          \"type\":\"input\"\n        },\n        {\n          \"referenceId\":\"engine-output\",\n          \"mode\":\"chunk\",\n          \"type\":\"output\"\n        }\n      ]\n    }\n    ,\n    {\n      \"engineId\":\"8eccf9cc-6b6d-4d7d-8cb3-7ebf4950c5f3\",\n      \"executionPreferences\":{\n        \"priority\":{{#if priority}} {{{priority}}} {{else}} \"-20\", {{/if}}\n        \"parentCompleteBeforeStarting\":true\n      },\n      \"ioFolders\":[\n        {\n          \"referenceId\":\"ow-input\",\n          \"mode\":\"chunk\",\n          \"type\":\"input\"\n        }\n      ]\n    }\n  ],\n  \"routes\":[\n    {\n      \"parentIoFolderReferenceId\":\"wsa-output\",\n      \"childIoFolderReferenceId\":\"si-input\"\n    },\n    {\n      \"parentIoFolderReferenceId\":\"si-output\",\n      \"childIoFolderReferenceId\":\"engine-input\"\n    },\n    {\n      \"parentIoFolderReferenceId\":\"engine-output\",\n      \"childIoFolderReferenceId\":\"ow-input\"\n    }\n  ]\n}\n", "templateLanguage": "Handlebars"}',
    '{"template": "{\n  \"target\":{\n    {{#if tdoName}} \"name\":\"{{{tdoName}}}\", {{/if}}\n    {{#if tdoDescription}} \"description\":\"{{{tdoDescription}}}\", {{/if}}\n    \"status\":\"downloaded\"\n  },\n  {{#if clusterId}} \"clusterId\":\"{{{clusterId}}}\", {{/if}}\n  {{#if notificationUri}} \"notificationUris\":[\"{{{notificationUri}}}\"], {{/if}}\n  \"tasks\":[\n    {\n      \"engineId\":\"9e611ad7-2d3b-48f6-a51b-0a1ba40fe255\",\n      \"payload\":{\n        \"url\":\"{{{UPLOAD_URL}}}\"\n      },\n      \"executionPreferences\":{\n        \"priority\":{{#if priority}} {{{priority}}} {{else}} \"-20\" {{/if}}\n      },\n      \"ioFolders\":[\n        {\n          \"referenceId\":\"wsa-output\",\n          \"mode\":\"stream\",\n          \"type\":\"output\"\n        }\n      ]\n    },\n    {\n      \"engineId\":\"352556c7-de07-4d55-b33f-74b1cf237f25\",\n      \"executionPreferences\":{\n        \"priority\":{{#if priority}} {{{priority}}} {{else}} \"-20\", {{/if}}\n        \"parentCompleteBeforeStarting\":true\n      },\n      \"ioFolders\":[\n        {\n          \"referenceId\":\"pb-input\",\n          \"mode\":\"stream\",\n          \"type\":\"input\"\n        }\n      ]\n    },\n    {\n      \"engineId\":\"8bdb0e3b-ff28-4f6e-a3ba-887bd06e6440\",\n      \"payload\":{\n        \"ffmpegTemplate\":\"audio\",\n        \"customFFMPEGProperties\":{\n          \"chunkSizeInSeconds\":{{#if chunkSizeInSeconds}} \"{{{chunkSizeInSeconds}}}\" {{else}} \"300\" {{/if}}\n        }\n      },\n      \"executionPreferences\":{\n        \"priority\":{{#if priority}} {{{priority}}} {{else}} \"-20\", {{/if}}\n        \"parentCompleteBeforeStarting\":true\n      },\n      \"ioFolders\":[\n        {\n          \"referenceId\":\"si-input\",\n          \"mode\":\"stream\",\n          \"type\":\"input\"\n        },\n        {\n          \"referenceId\":\"si-output\",\n          \"mode\":\"chunk\",\n          \"type\":\"output\"\n        }\n      ]\n    },\n    {\n      \"engineId\":\"{{{ENGINE_ID}}}\",\n      \"payload\":{\n        {{#if diarise}} \"diarise\":\"{{{diarise}}}\", {{/if}}\n        {{#if keywords}} \"keywords\":\"{{{keywords}}}\", {{/if}}\n        \"COMMA_CATCHER\":\"true\"\n      },\n      \"executionPreferences\":{\n        \"priority\":{{#if priority}} {{{priority}}} {{else}} \"-20\", {{/if}}\n        \"parentCompleteBeforeStarting\":true\n      },\n      \"ioFolders\":[\n        {\n          \"referenceId\":\"engine-input\",\n          \"mode\":\"chunk\",\n          \"type\":\"input\"\n        },\n        {\n          \"referenceId\":\"engine-output\",\n          \"mode\":\"chunk\",\n          \"type\":\"output\"\n        }\n      ]\n    }\n    ,\n    {\n      \"engineId\":\"8eccf9cc-6b6d-4d7d-8cb3-7ebf4950c5f3\",\n      \"executionPreferences\":{\n        \"priority\":{{#if priority}} {{{priority}}} {{else}} \"-20\", {{/if}}\n        \"parentCompleteBeforeStarting\":true\n      },\n      \"ioFolders\":[\n        {\n          \"referenceId\":\"ow-input\",\n          \"mode\":\"chunk\",\n          \"type\":\"input\"\n        }\n      ]\n    }\n  ],\n  \"routes\":[\n    {\n      \"parentIoFolderReferenceId\":\"wsa-output\",\n      \"childIoFolderReferenceId\":\"pb-input\"\n    },\n    {\n      \"parentIoFolderReferenceId\":\"wsa-output\",\n      \"childIoFolderReferenceId\":\"si-input\"\n    },\n    {\n      \"parentIoFolderReferenceId\":\"si-output\",\n      \"childIoFolderReferenceId\":\"engine-input\"\n    },\n    {\n      \"parentIoFolderReferenceId\":\"engine-output\",\n      \"childIoFolderReferenceId\":\"ow-input\"\n    }\n  ]\n}\n", "templateLanguage": "Handlebars"}'
  )
ON CONFLICT ("engine_id") DO NOTHING;

UPDATE job_new.build SET build_state = 'paused'
  WHERE engine_id = 'c0e55cde-340b-44d7-bb42-2e0d65e98255' AND build_id != '7b6b8ea3-c0cd-4ae2-8857-64cdad787da4' AND build_state = 'deployed';

INSERT INTO job_new.build
  (
    "engine_id",
    "build_id",
    "version",
    "build_state",
    "price",
    "created_date",
    "updated_date",
    "deployment_model",
    "docker_image",
    "task_runtime",
    "is_legacy",
    "vul_low_count",
    "vul_medium_count",
    "vul_high_count",
    "vul_critical_count",
    "build_size",
    "deploy_date",
    "manifest",
    "data_certified"
  )
VALUES
  (
    'c0e55cde-340b-44d7-bb42-2e0d65e98255',
    '7b6b8ea3-c0cd-4ae2-8857-64cdad787da4',
    16,
    'deployed',
    125,
    1621377770,
    1621377770,
    0,
    'registry.central.aiware.com/c0e55cde-340b-44d7-bb42-2e0d65e98255:7b6b8ea3-c0cd-4ae2-8857-64cdad787da4',
    '{"edge": {}}',
    FALSE,
    NULL,
    NULL,
    NULL,
    NULL,
    3385267901,
    NULL,
    '{"url": "https://github.com/veritone/speechmatics-container-service/", "user": "kmurray+cs@veritone.com", "build": "7b6b8ea3-c0cd-4ae2-8857-64cdad787da4", "oauth": "", "runtime": "", "category": "Transcription", "engineId": "c0e55cde-340b-44d7-bb42-2e0d65e98255", "isPublic": true, "schedule": "", "schemaId": 0, "sourceId": 0, "ingestion": {"scanner": false, "supportsLiveStreams": false, "supportedSourceTypes": null}, "libraries": null, "maxFileMb": 0, "categories": null, "engineMode": "chunk", "clusterSize": "custom", "isBenchmark": false, "isConductor": false, "useCustomUI": false, "gpuSupported": "", "inputOptions": null, "releaseNotes": "Build Information: [2021-05-18_21:50:30] [master - c8daf7e1bfc64be534dd62807e0b390de651dc78] en:7.0.0; Is speaker separation engine: false", "customProfile": "speechmatics", "externalCalls": [], "inputEncoding": "", "outputFormats": ["application/json"], "serverCountry": "", "volumeProfile": "", "maxConcurrency": 50, "isCJISCompliant": false, "trainableViaApi": false, "whitelistOrgIds": null, "maxMediaLengthMs": 0, "minMediaLengthMs": 0, "fedRampImpactLevel": 0, "initialConcurrency": 50, "sourceFileDeletion": false, "supportedLanguages": null, "preferredInputFormat": "application/json", "supportedInputFormats": ["audio/mp4", "audio/flac", "audio/wav", "audio/mpeg"]}',
    NULL
  )
ON CONFLICT ("build_id") DO NOTHING;

-- Engine 414eb717-388e-4082-9a04-65dec0b739bd with deployed build 1882275e-9896-4380-ad92-521d939cdbf8:
INSERT INTO job_new.engine
  (
    "engine_id",
    "engine_category_id",
    "engine_name",
    "engine_description",
    "engine_state",
    "deployment_model",
    "owner_organization_id",
    "is_public",
    "price",
    "rating",
    "website",
    "logo_path",
    "order",
    "dependency",
    "core_job_data",
    "fields",
    "validation",
    "application_id",
    "asset",
    "creates_recording",
    "deleted",
    "created_date",
    "updated_date",
    "library_required",
    "icon_path",
    "engine_currency",
    "engine_alias_id",
    "engine_alias_name",
    "engine_alias_description",
    "engine_alias_logo_path",
    "jwt_rights",
    "use_cases",
    "industries",
    "engine_manifest",
    "edge_version",
    "single_engine_tdo_job_json",
    "single_engine_upload_job_json"
  )
VALUES
  (
    '414eb717-388e-4082-9a04-65dec0b739bd',
    'f951fbf9-aa69-47a2-87c8-12dfb51a1f18',
    'Illuminate Export to Desktop V3',
    'illuminate export to desktop v3f',
    'active',
    1,
    7682,
    TRUE,
    NULL,
    NULL,
    NULL,
    NULL,
    100,
    NULL,
    '{"category": "utility", "dependencies": ["ingestion"]}',
    '[]',
    NULL,
    NULL,
    NULL,
    FALSE,
    FALSE,
    1577094678,
    1607937176,
    FALSE,
    NULL,
    'USD',
    '414eb717-388e-4082-9a04-65dec0b739bd',
    NULL,
    NULL,
    NULL,
    '{"roles": [{"roleName": "conductor", "taskRights": ["job:create"], "assetRights": []}]}',
    '[]',
    '[]',
    NULL,
    3,
    NULL,
    NULL
  )
ON CONFLICT ("engine_id") DO NOTHING;

UPDATE job_new.build SET build_state = 'paused'
  WHERE engine_id = '414eb717-388e-4082-9a04-65dec0b739bd' AND build_id != '1882275e-9896-4380-ad92-521d939cdbf8' AND build_state = 'deployed';

INSERT INTO job_new.build
  (
    "engine_id",
    "build_id",
    "version",
    "build_state",
    "price",
    "created_date",
    "updated_date",
    "deployment_model",
    "docker_image",
    "task_runtime",
    "is_legacy",
    "vul_low_count",
    "vul_medium_count",
    "vul_high_count",
    "vul_critical_count",
    "build_size",
    "deploy_date",
    "manifest",
    "data_certified"
  )
VALUES
  (
    '414eb717-388e-4082-9a04-65dec0b739bd',
    '1882275e-9896-4380-ad92-521d939cdbf8',
    53,
    'deployed',
    NULL,
    1621293794,
    1621293794,
    0,
    'registry.central.aiware.com/414eb717-388e-4082-9a04-65dec0b739bd:1882275e-9896-4380-ad92-521d939cdbf8',
    '{"edge": {}}',
    FALSE,
    NULL,
    NULL,
    NULL,
    NULL,
    58433927,
    NULL,
    '{"url": "https://github.com/veritone/task-illuminate-export-to-desktop", "user": "jlu+superadmin@veritone.com", "build": "1882275e-9896-4380-ad92-521d939cdbf8", "oauth": "", "runtime": "", "category": "document", "engineId": "414eb717-388e-4082-9a04-65dec0b739bd", "isPublic": true, "schedule": "", "schemaId": 0, "sourceId": 0, "ingestion": {"scanner": false, "supportsLiveStreams": false, "supportedSourceTypes": null}, "libraries": null, "maxFileMb": 0, "categories": null, "engineMode": "batch", "clusterSize": "xlarge", "isBenchmark": false, "isConductor": false, "useCustomUI": false, "gpuSupported": "", "inputOptions": null, "releaseNotes": "", "customProfile": "", "externalCalls": [], "inputEncoding": "", "outputFormats": ["application/json"], "serverCountry": "", "volumeProfile": "", "maxConcurrency": 50, "isCJISCompliant": false, "trainableViaApi": false, "whitelistOrgIds": null, "maxMediaLengthMs": 0, "minMediaLengthMs": 0, "fedRampImpactLevel": 0, "initialConcurrency": 50, "sourceFileDeletion": false, "supportedLanguages": null, "preferredInputFormat": "video/mp4", "supportedInputFormats": ["video/mp4"]}',
    NULL
  )
ON CONFLICT ("build_id") DO NOTHING;