const LAST_URL_KEY = 'lastURL';
const PREV_URLS_KEY = 'previousURLs';
const DEFAULT_QUERY = `
# Write your query or mutation here
`;

const PLAYGROUND_ENDPOINT = process.env.PLAYGROUND_ENDPOINT;
const PLAYGROUND_SUBSCRIPTION_ENDPOINT =
  process.env.PLAYGROUND_SUBSCRIPTION_ENDPOINT;

const URL_PLACEHOLDERS = {
  url: '{{PLAYGROUND_ENDPOINT}}'
};

const THEME_PLACEHOLDER = '{{THEME}}';

module.exports = {
  LAST_URL_KEY,
  PREV_URLS_KEY,
  DEFAULT_QUERY,

  PLAYGROUND_ENDPOINT,
  PLAYGROUND_SUBSCRIPTION_ENDPOINT,
  URL_PLACEHOLDERS,
  THEME_PLACEHOLDER
};
