const _ = require('lodash');

async function helpCreatePackage(client, input) {
  const { gqlClient, options } = client;
  const { resources } = input;

  let resourcesString = '';
  if (!_.isEmpty(resources)) {
    resourcesString = resources.reduce((query, record) => {
      query += `
        {
          resourceId: "${record.resourceId}"
          resourceType: ${record.resourceType}
          action: ${record.action}
        },`;

      return query;
    }, ``);
    resourcesString = `resources: [${resourcesString}]`;
  }

  const createPackageQuery = `
    mutation createPackage (
      $id: ID
      $organizationId: ID
      $name: String!
      $description: String
      $icon: String
      $distributionType: EngineDistributionType
      $version: String!
      #$resources: [PackageResourceInput]
      $primaryResourceId: ID
      $sourceOriginId: ID
      $sourcePackageId: ID
      $aiwareVersion: String
      $status: PackageStatus
      $installDate: DateTime
      $deleted: Boolean
      $packageCreatedDate: DateTime
      $autoGenerated: Boolean
    ) {
      packageCreate(
        input: {
          id: $id
          organizationId: $organizationId
          name: $name
          description: $description
          icon: $icon
          distributionType: $distributionType
          version: $version
          primaryResourceId: $primaryResourceId
          sourceOriginId: $sourceOriginId
          sourcePackageId: $sourcePackageId
          aiwareVersion: $aiwareVersion
          status: $status
          installDate: $installDate
          deleted: $deleted
          packageCreatedDate: $packageCreatedDate
          autoGenerated: $autoGenerated
          ${resourcesString}
        }
      ) {
        id
        resources {
          records {
            id
            resourceType
            resourceAlias
          }
        }
      }
    }
  `;

  return gqlClient.query(createPackageQuery, input, options);
}

async function helpGetPackages(client, input) {
  const { gqlClient, options } = client;
  const packagesQuery = `
    query packages (
      $id: ID
      $ids: [ID!]
      $orgId: ID
      $resourceId: ID
      $resourceAlias: String
      $primaryResourceId: ID
      $sourceOriginId: ID
      $sourcePackageId: ID
      $packageFilter: PackageFilter
      $status: PackageStatus
      $nameRegexp: String
      $owned: Boolean
      $includeDeleted: Boolean
      $offset: Int
      $limit: Int
    ) {
    packages (
      id: $id
      ids: $ids
      orgId: $orgId
      resourceId: $resourceId
      resourceAlias: $resourceAlias
      primaryResourceId: $primaryResourceId
      sourceOriginId: $sourceOriginId
      sourcePackageId: $sourcePackageId
      packageFilter: $packageFilter
      status: $status
      nameRegexp: $nameRegexp
      owned: $owned
      includeDeleted: $includeDeleted
      offset: $offset
      limit: $limit
    ) {
      records {
        id
        name
        status
        organization {
          id
        }
        primaryResource {
          resourceId
          resourceType
        }
      }
    }
  }`;
  return gqlClient.query(packagesQuery, input, options);
}

async function helpDeletePackage(client, input) {
  const { gqlClient, options } = client;
  const deletePackageQuery = `
    mutation {
      packageDelete(id: "${input.id}") {
        success
        msg
        code
      }
    }
  `;

  return gqlClient.query(deletePackageQuery, {}, options);
}

async function helpGetGrantedPackage(client, input) {
  const { gqlClient, options } = client;
  const grantsQuery = `
    query getGrantPackage (
      $id: ID
      $orgId: ID
      $includeDeleted: Boolean = false
      $offset: Int
      $limit: Int
      $packageFilter: PackageGrantFilter
    ) {
      packageGrants(
        id: $id
        orgId: $orgId
        includeDeleted: $includeDeleted
        offset: $offset
        limit: $limit
        packageFilter: $packageFilter
      ) {
        records {
          package { id }
        }
      }
    }
  `;
  return gqlClient.query(grantsQuery, input, options);
}

async function helpUpdatePackageGrant(client, input) {
  const { gqlClient, options } = client;
  const { packageGrants, packageId } = input;

  let packageGrantString = '';
  if (!_.isEmpty(packageGrants)) {
    packageGrantString = packageGrants.reduce((query, record) => {
      query += `
        {
          organizationId: ${record.organizationId}
          action: ${record.action}
          grantType: ${record.grantType}
        },`;

      return query;
    }, ``);
  }

  const queryGrant = `
    mutation addGrant {
      packageUpdateGrants(
        input: {
          packageId: "${packageId}"
          packageGrants: [${packageGrantString}]
        }
      ) {
        id
        name
        version
      }
    }`;
  return gqlClient.query(queryGrant, {}, options);
}

module.exports = {
  helpCreatePackage,
  helpGetPackages,
  helpDeletePackage,
  helpGetGrantedPackage,
  helpUpdatePackageGrant
};
