const _ = require('lodash');

module.exports = function createFunction(serviceContext) {
  const cache = require('./cache.js')(serviceContext);
  const packages = require('../dal/package.js')(serviceContext);
  const util = require('./util.js')(serviceContext);

  return {
    grantType: (obj) => obj.grantType || null,
    name: async (obj, args, context) => {
      if (!obj.autoGenerated) return obj.name;

      // this function checks to see if the name is the old naming convention
      // if so, it will update the name of the package to it's primary resource's name
      // if not, it returns the current name
      return await packages.backFillAppPackageNames(obj, context);
    },
    icon: (obj) => util.getSignedUrlOrVirtual(obj.icon),
    createdBy: async (object, args, context) => {
      const user = await serviceContext.dal.admin.getUserBasicInfo(
        { userId: object.createdBy },
        context
      );
      return {
        ...user,
        id: user.userId,
        name: `${user.firstName} ${user.lastName}`
      };
    },
    modifiedBy: async (object, args, context) => {
      const user = await serviceContext.dal.admin.getUserBasicInfo(
        { userId: object.modifiedBy },
        context
      );
      return {
        ...user,
        id: user.userId,
        name: `${user.firstName} ${user.lastName}`
      };
    },
    resources: async (object, args, context) => {
      return packages.getPackageResources(context, {
        packageId: object.packageId,
        resourceType: args.type,
        resourceAlias: args.alias,
        limit: args.limit,
        offset: args.offset
      });
    },
    nestedResources: async (object, args, context) => {
      return await packages.getNestedResources(context, {
        packageId: object.packageId,
        resourceType: args.type,
        limit: args.limit,
        offset: args.offset
      });
    },
    primaryResource: async (object, args, context) => {
      if (_.isNil(object.primaryResourceId)) return null;

      const resources = await packages.getPackageResources(context, {
        resourceId: object.primaryResourceId
      });
      return _.get(resources, 'records[0]');
    },
    organization: (object, args, context) => {
      if (!object.organizationId || object.organizationId === 'internal') {
        return null;
      }

      if (context.skipCache === true) {
        return serviceContext.dal.organization.getOrganization(
          context,
          {
            id: object.organizationId
          },
          true
        );
      }

      return cache.get(
        context,
        { id: object.organizationId },
        'Organization',
        () =>
          serviceContext.dal.organization.getOrganization(context, {
            id: object.organizationId
          })
      );
    }
  };
};
