const _ = require('lodash');
const { v4: uuidv4 } = require('uuid');
const moment = require('moment');
const validator = require('validator');
const mapper = require('./mapper');

const {
  eventsMap,
  supportedEvents
} = require('@veritone/core-server-base/events-map.js');

const SYSTEM_APPLICATION_ID = 'system';
const SERVICE_NAME = 'core-graphql-server';

const connectionStringKeys = {
  core: 'core',
  mediaPlatform: 'media_platform'
};

const aiWAREVersionTableName = 'aiware.aiware_version';
const aiWAREVersionHistoryTableName = 'aiware.aiware_version_history';
const platformInfoTableName = 'aiware.platform_info';
const loginConfigurationTableName = 'public.login_configuration';

module.exports = function createFunction(serviceContext) {
  const { config, logger } = serviceContext;
  const mainUtil = require('../util.js')(serviceContext);
  const dalUtil = require('./util')(config, serviceContext);
  const resUtil = require('../resolvers/util.js')(serviceContext);
  const errors = require('../error')(config);
  const localCache =
    serviceContext.localCache || require('../localCache')(serviceContext);
  const messageUtil = serviceContext.messageUtil;

  const PlatformVersionStates = {
    Current: 'Current',
    Previous: 'Previous',
    Next: 'Next',
    Unavailable: 'Unavailable'
  };

  const {
    InvalidInput,
    NotFound,
    NotAllowed,
    ServiceFailure
  } = require('../error')(config);

  const dbRead = serviceContext.dbConnections[connectionStringKeys.core].read;
  const dbWrite = serviceContext.dbConnections[connectionStringKeys.core].write;
  const dbReadLoginConfig =
    serviceContext.dbConnections[connectionStringKeys.mediaPlatform].read;
  const dbWriteLoginConfig =
    serviceContext.dbConnections[connectionStringKeys.mediaPlatform].write;

  const aiWAREVersionColumns = {
    id: null,
    version: null,
    original_manifest_url: null,
    original_change_log_url: null,
    original_highlights_url: null,
    manifest_url: null,
    change_log_url: null,
    highlights_url: null,
    created_by: null,
    created_at: null,
    installed_by: null,
    installed_at: null
  };

  const aiWAREVersionOrderByMap = {
    version: 'version',
    createdAt: 'created_at',
    installedAt: 'installed_at'
  };

  const orderDirectionMap = {
    desc: 'DESC',
    asc: 'ASC'
  };

  const platformInfoColumns = {
    json_properties: null,
    modified_by: null,
    modified_at: null
  };

  const loginConfigColumns = {
    name: null,
    slug: null,
    logo: null,
    login_button_style: null,
    organization_id: null,
    created_by: null,
    modified_by: null,
    enabled: null,
    hide_veritone_branding: null
  };

  const auditLogExportRequestStatus = {
    pending: 'PENDING',
    in_progress: 'IN_PROGRESS',
    completed: 'COMPLETED',
    failed: 'FAILED',
    cancelled: 'CANCELLED'
  };

  function reverseStatusLookup(value) {
    const entry = Object.entries(auditLogExportRequestStatus).find(
      ([key, val]) => val === value
    );
    return entry ? entry[0] : new Error('Invalid status value');
  }

  async function formatAuditLogExportRequestResponse(exportReq) {
    const { status, filters = {}, downloadUrl } = exportReq;

    let formattedDateTimeFilter;
    const dateTimeFilter = filters.dateTimeFilter;
    if (dateTimeFilter) {
      formattedDateTimeFilter = {
        fromDateTime: moment(
          _.get(dateTimeFilter, 'fromDateTime')
        ).toISOString(),
        toDateTime: moment(_.get(dateTimeFilter, 'toDateTime')).toISOString()
      };
    }

    let signedDownloadUrl = downloadUrl;
    if (downloadUrl) {
      signedDownloadUrl = await serviceContext.storage.getSignedUrlPromise(
        downloadUrl
      );
    }

    return {
      ...exportReq,
      filters: {
        ...filters,
        dateTimeFilter: formattedDateTimeFilter
          ? formattedDateTimeFilter
          : undefined
      },
      status: auditLogExportRequestStatus[status],
      downloadUrl: signedDownloadUrl
    };
  }

  /**
   * This function adds a platform version to the aiware_version table.
   * This only establishes a version, but it does not set it as the
   * currently installed version. Use the setCurrentPlatform version
   * to set the state to installed (aka 'current').
   * @param {Object} context The request context
   * @param {Object} args contain input with organizationId
   * @returns {Object} Returns a single object of all fields including
   * the id, which may have already been generated by the calling client
   * or within the dal.
   */
  async function addPlatformVersion(context, args) {
    const { input } = args;
    let version = input.version;
    const { userInfo, tokenInfo } = context.requestContext;
    const assemblePayload = (version, createdPlatformVersion, err) => ({
      serviceName: SERVICE_NAME,
      id: uuidv4(),
      version,
      versionId: _.get(createdPlatformVersion, 'id'),
      createdBy: _.get(createdPlatformVersion, 'createdBy'),
      // actionInfo
      actionInfo: messageUtil.buildActionInfo(
        _.get(createdPlatformVersion, 'id'),
        err,
        'create',
        !err ? 'success' : 'failure',
        !err
          ? `Created platform version ${version}`
          : 'Failed to create new platform version'
      )
    });
    const emitNewPlatformVersionAvailableEvent = async (
      version,
      createdPlatformVersion,
      err
    ) => {
      const event = assemblePayload(version, createdPlatformVersion, err);
      serviceContext.messageUtil.emitPublicEvent(
        supportedEvents.NewVersionAvailable,
        SYSTEM_APPLICATION_ID,
        context,
        event
      );
    };
    const emitNewVersionAuditEvent = async (
      version,
      createdPlatformVersion,
      err
    ) => {
      const event = assemblePayload(version, createdPlatformVersion, err);
      serviceContext.messageUtil.emitPublicEvent(
        supportedEvents.PlatformNewVersionAvailable,
        SYSTEM_APPLICATION_ID,
        context,
        event
      );
    };
    try {
      if (_.isNil(input)) {
        throw new InvalidInput({
          message: `The required input object was not found.`
        });
      }

      let userId = _.get(userInfo, 'userId') || _.get(tokenInfo, 'userId');
      if (_.isNil(userId)) {
        // If user info could not be gathered from the token, then assume this
        // is a user-less API token
        userId = 'aiWareInstanceAdmin';
      }

      if (input.id && !validator.isUUID(input.id)) {
        throw new InvalidInput({
          message: `Invalid ID format '${input.id}'. ID must be in the UUID format.`
        });
      }

      if (!version) {
        throw new InvalidInput({
          message: 'The version is a required field.'
        });
      }

      if (!input.manifestUrl) {
        input.manifestUrl = '';
      }

      if (!input.changeLogUrl) {
        input.changeLogUrl = '';
      }

      if (!input.highlightsUrl) {
        input.highlightsUrl = '';
      }

      // if id not supplied, generate one
      let id = input.id;
      if (!id) {
        id = uuidv4();
      }

      let columnData = {
        id: id,
        version: version,
        manifestUrl: input.manifestUrl,
        changeLogUrl: input.changeLogUrl,
        highlightsUrl: input.highlightsUrl,
        originalManifestUrl: input.manifestUrl,
        originalChangeLogUrl: input.changeLogUrl,
        originalHighlightsUrl: input.highlightsUrl,
        createdBy: userId
      };

      let createdPlatformVersion = columnData;
      const { isExisting } = await getVersionCompatability(version);
      if (!isExisting) {
        columnData = mapper.decamelizeRootKeys(columnData);

        const { sql, values } = mainUtil.makeInsertSql(
          aiWAREVersionTableName,
          columnData,
          aiWAREVersionColumns
        );

        try {
          createdPlatformVersion = await dbWrite.one(
            sql,
            values,
            mapper.camelizeRootKeys
          );
        } catch (err) {
          throw new Error('Unable to add a new platform version entry.');
        }
        emitNewPlatformVersionAvailableEvent(version, createdPlatformVersion);
      } else {
        //The version already exists. Return that existing version information.
        createdPlatformVersion = await getVersion(context, version);
      }
      emitNewVersionAuditEvent(version, createdPlatformVersion);
      return createdPlatformVersion;
    } catch (err) {
      emitNewVersionAuditEvent(version, null, err);
      throw err;
    }
  }

  /**
   * This function takes a valid version that is located in the
   * aiware_version table and stamps the installed_by and installed_at
   * fields. While having MAX(installed_at) date makes the version,
   * the 'current' version.
   * @param {Object} context The request context
   * @param {Object} args contain input with organizationId
   * @returns {Object} Returns a single object of all aiware_version fields.
   */
  async function setCurrentPlatformVersion(context, args) {
    const { version } = args;
    const { userInfo, tokenInfo } = context.requestContext;
    const assemblePayload = (currentPlatformVersion, err) => ({
      serviceName: SERVICE_NAME,
      id: uuidv4(),
      version,
      versionId: _.get(currentPlatformVersion, 'id'),
      installedAt: moment(
        _.get(currentPlatformVersion, 'installedAt')
      ).toISOString(),
      installedBy: _.get(currentPlatformVersion, 'installedBy'),
      createdBy: _.get(currentPlatformVersion, 'createdBy'),
      // actionInfo
      actionInfo: messageUtil.buildActionInfo(
        _.get(currentPlatformVersion, 'id'),
        err,
        'update',
        !err ? 'success' : 'failure',
        !err
          ? `Installed platform version ${version}`
          : `Failed to install platform version ${version}`
      )
    });

    const emitNewPlatformVersionInstalledEvent = async (
      currentPlatformVersion,
      err
    ) => {
      const event = assemblePayload(currentPlatformVersion, err);
      serviceContext.messageUtil.emitPublicEvent(
        supportedEvents.NewVersionInstalled,
        SYSTEM_APPLICATION_ID,
        context,
        event
      );
    };

    const emitVersionInstalledAuditEvent = async (
      currentPlatformVersion,
      err
    ) => {
      const event = assemblePayload(currentPlatformVersion, err);
      serviceContext.messageUtil.emitPublicEvent(
        supportedEvents.PlatformNewVersionInstalled,
        SYSTEM_APPLICATION_ID,
        context,
        event
      );
    };
    let userId = _.get(userInfo, 'userId') || _.get(tokenInfo, 'userId');
    if (_.isNil(userId)) {
      // If user info could not be gathered from the token, then assume this
      // is a user-less API token
      userId = 'aiWareInstanceAdmin';
    }

    try {
      let validVersion = version;
      if (!validVersion) {
        throw new InvalidInput({
          message: 'The version is a required field.'
        });
      }

      // The version must exist
      const { isExisting, currentVersion } = await getVersionCompatability(
        version
      );

      let currentPlatformVersion;
      if (currentVersion !== version) {
        if (!isExisting) {
          throw new Error(
            `The input version, '${validVersion}' does not exist`
          );
        }

        const values = [userId, version];

        const returningData = mainUtil.makeSelectClause(aiWAREVersionColumns);

        const sql = `-- set the version to installed
                    UPDATE
                        ${aiWAREVersionTableName}
                    SET
                      installed_at = NOW(),
                      installed_by = $1
                    WHERE
                      version = $2;
  
                    -- add to version history
                    INSERT INTO
                      ${aiWAREVersionHistoryTableName}(
                        version_id,
                        installed_at,
                        installed_by
                      )
                      SELECT
                        id,
                        installed_at,
                        installed_by
                      FROM
                        ${aiWAREVersionTableName}
                      WHERE
                        version = $2;
                      
                    -- return this data
                    SELECT
                      ${returningData}
                    FROM
                      ${aiWAREVersionTableName}
                    WHERE 
                      version = $2;`;

        context.tx = dbWrite;
        try {
          currentPlatformVersion = await dbWrite.one(
            sql,
            values,
            mapper.camelizeRootKeys
          );
        } catch (err) {
          throw new Error('Unable to set the current version.');
        }
      } else {
        // The current version is already set. Return the current version.
        currentPlatformVersion = await getVersion(context, version);
      }
      emitNewPlatformVersionInstalledEvent(currentPlatformVersion);
      emitVersionInstalledAuditEvent(currentPlatformVersion);
      return currentPlatformVersion;
    } catch (err) {
      emitNewPlatformVersionInstalledEvent(null, err);
      emitVersionInstalledAuditEvent(null, err);
      throw err;
    }
  }

  async function setPlatformProperties(context, args) {
    const { properties } = args;
    const { userInfo, tokenInfo } = context.requestContext;

    if (!properties) {
      throw new InvalidInput({
        message: 'The properties is a required field.'
      });
    }

    if (!_.isObject(properties)) {
      throw new InvalidInput({
        message: 'The properties field must be an object.'
      });
    }

    let userId = _.get(userInfo, 'userId') || _.get(tokenInfo, 'userId');
    if (_.isNil(userId)) {
      // If user info could not be gathered from the token, then assume this
      // is a user-less API token
      userId = 'aiWareInstanceAdmin';
    }

    const inputJsonProperties = JSON.stringify(properties);
    const sql = `UPDATE aiware.platform_info
      SET
        json_properties = json_properties || $1::jsonb,
        modified_by = $2,
        modified_at = NOW()
      WHERE
        1=1
      RETURNING
        json_properties,
        modified_by,
        modified_at
      ;`;
    const values = [inputJsonProperties, userId];

    let updatedProperties;
    try {
      updatedProperties = await dbWrite.one(
        sql,
        values,
        mapper.mapPlatformProperties
      );
    } catch (err) {
      throw new Error('Unable to set the platform properties.');
    }

    return updatedProperties;
  }

  /**
   * This function returns the three most interesting states located in the
   * aiware_version table: current, next, and previous.
   * @param {Object} context The request context
   * @param {Object} args contain input with organizationId
   * @returns {Object} This object is a container of three objects: currentVersion,
   * nextVersion, and previousVersion. Each of those three objects contain all fields
   * avaiable from the aiware_version table for there respective state.
   */
  async function getAIWAREVersion(context, args) {
    let response = {
      aiWAREVersion: {
        currentVersion: null,
        nextVersion: null,
        previousVersion: null
      }
    };

    const selectColumns = mainUtil.makeSelectClause(aiWAREVersionColumns);

    const versionSQL = `
      -- next version
      (SELECT '${PlatformVersionStates.Next}' version_state, ${selectColumns} FROM ${aiWAREVersionTableName} WHERE created_at > (SELECT COALESCE(created_at, '0001-01-01 00:00:00') FROM ${aiWAREVersionTableName} WHERE installed_at IS NOT NULL ORDER BY installed_at DESC LIMIT 1) ORDER BY created_at DESC LIMIT 1)
      UNION
      -- current version
      (SELECT '${PlatformVersionStates.Current}' version_state, ${selectColumns} FROM ${aiWAREVersionTableName} WHERE installed_at IS NOT NULL ORDER BY installed_at DESC LIMIT 1)
      UNION
      -- previous version
      (SELECT '${PlatformVersionStates.Previous}' version_state, ${selectColumns} FROM ${aiWAREVersionTableName} WHERE installed_at IS NOT NULL ORDER BY installed_at DESC LIMIT 1 OFFSET 1)
      UNION ALL
      -- default three blank rows
      (SELECT 
        '${PlatformVersionStates.Unavailable}' version_state,
        'ffffffff-ffff-ffff-ffff-ffffffffffff' AS id, 
        '' AS version, 
        '' AS original_manifest_url,
        '' AS original_changelog_url,
        '' AS original_highlights_url,
        '' AS manifest_url,
        '' AS changelog_url,
        '' AS highlights_url,
        'ffffffff-ffff-ffff-ffff-ffffffffffff' AS created_by,
        '1/1/1970' AS created_at,
        NULL AS installed_by,
        NULL AS installed_at
      FROM 
        generate_series(1, 3) AS three_default_rows)
      -- only ever return 3 rows, where the non-null rows will supercede the default blank rows
      LIMIT 3
    `;

    try {
      const results = await dbRead.map(versionSQL, [], mapper.camelizeRootKeys);

      // default return state data to unavailable
      for (let row of results) {
        if (row.versionState === PlatformVersionStates.Unavailable) {
          // only worry about defaulting the current version for now
          response.aiWAREVersion.currentVersion = row;
          break;
        }
      }

      // apply specific states to return data, if any
      for (let row of results) {
        if (row.versionState === PlatformVersionStates.Current) {
          response.aiWAREVersion.currentVersion = row;
        } else if (row.versionState === PlatformVersionStates.Previous) {
          response.aiWAREVersion.previousVersion = row;
        } else if (row.versionState === PlatformVersionStates.Next) {
          response.aiWAREVersion.nextVersion = row;
        }
      }
    } catch (err) {
      throw new Error('Unable to retrieve the platform versions.');
    }

    return response;
  }

  async function getAIWAREVersionHistory(context, args) {
    let aiWAREVersionHistory = [];
    // get sql query
    const { sql, sqlArgs, pageArgs } = _getAIWAREVersionHistorySql(args);

    try {
      const results = await dbRead.map(
        sql,
        sqlArgs,
        mapper.mapPlatformVersionHistory
      );
      aiWAREVersionHistory = mainUtil.toPage(pageArgs, results);
    } catch (err) {
      logger.error('Unable to retrieve the platform version history.', err);
      throw new Error('Unable to retrieve the platform version history.');
    }

    return aiWAREVersionHistory;
  }

  function _getAIWAREVersionHistorySql(args) {
    let { limit, offset, versions, ids } = args || {};

    const sqlArgs = [];
    const conditions = [];
    // Filter by version ids
    let _ids = [];
    if (!_.isNil(ids)) {
      if (_.isArray(ids)) {
        _ids = ids;
      } else {
        _ids.push(ids);
      }
      sqlArgs.push(_ids);
      conditions.push(` v.id = ANY($${sqlArgs.length}::uuid[])`);
    }
    // Filter by version
    let _versions = [];
    if (!_.isNil(versions)) {
      if (_.isArray(versions)) {
        _versions = versions;
      } else {
        _versions.push(versions);
      }
      sqlArgs.push(_versions);
      conditions.push(` v.version = ANY($${sqlArgs.length}::varchar[])`);
    }

    const versionSelectClause = mainUtil.makeSelectClause(
      aiWAREVersionColumns,
      'v'
    );
    // add the history
    let sql = `SELECT
                 ${versionSelectClause},
                  h.history_id,
                  h.installed_by,
                  h.installed_at,
                  h.created_at history_created_at
                FROM
                  ${aiWAREVersionTableName} v
                INNER JOIN ${aiWAREVersionHistoryTableName} h ON h.version_id = v.id
                ${
                  conditions.length === 0
                    ? ''
                    : ` WHERE ${conditions.join(' AND ')}`
                }
                ORDER BY h.installed_at DESC`;

    // Pagination
    if (!Number.isInteger(limit)) {
      limit = 30;
    }
    if (!Number.isInteger(offset)) {
      offset = 0;
    }

    sqlArgs.push(limit);
    sql += ` LIMIT \$${sqlArgs.length}`;

    sqlArgs.push(offset);
    sql += ` OFFSET \$${sqlArgs.length}`;

    return {
      sql,
      sqlArgs,
      pageArgs: { limit, offset }
    };
  }

  async function getPlatformProperties(context, args) {
    let properties;

    const selectColumns = mainUtil.makeSelectClause(platformInfoColumns);

    const sql = ` SELECT 
                    ${selectColumns} 
                  FROM 
                    ${platformInfoTableName}
                  LIMIT 1`;

    try {
      properties = await dbRead.one(sql, {}, mapper.mapPlatformProperties);
    } catch (err) {
      // throw handled below
    }

    if (!properties) {
      throw new Error(`Unable to retrieve platform properties.`);
    }

    return properties;
  }

  /**
   * This function takes a valid version and compares it
   * to the 'current' version (if one exists) in the aiware_version table.
   * In order to service existence of an input version,
   * the function also returns a boolean values to make that determination.
   * @param {Object} context The request context
   * @param {Object} args contain input with organizationId
   * @returns {Object}
   *  tipVersion: The most recenently submitted version number.
   *  currentVersion: A string belonging to the 'current' version (aka installed version)
   *  isExisting: The input version number was found in the aiware_version table.
   *    This does not provide any other information about its existence.
   *  createdAt: If the version is existing, the createdAt date is returned. This is to
   *    provide information when adding a version, but the version already exists and
   *    needs the required field to return.
   *
   */
  async function getVersionCompatability(version) {
    let comparison = {
      tipVersion: '',
      currentVersion: '',
      isExisting: false
    };

    const sql = `
      (
        (SELECT
          -- Tip most Version (highest version number, but may or may not be the currently installed version)
          version tip_version,
          -- Currently installed version
          (SELECT version FROM ${aiWAREVersionTableName} WHERE installed_at = (SELECT MAX(installed_at) FROM ${aiWAREVersionTableName})) current_version,
          -- Does the input version exist?
          (SELECT COUNT(*) FROM ${aiWAREVersionTableName} WHERE version = $1) is_existing
        FROM 
          ${aiWAREVersionTableName}
        ORDER BY 
          created_at DESC
        LIMIT 1)
        
        UNION ALL

        (SELECT NULL tip_version, NULL current_version, 0 is_existing) -- default SELECT when table is empty
      )
      LIMIT 1; -- return only 1 row for the UNION
    `;

    try {
      comparison = await dbRead.one(sql, [version], mapper.camelizeRootKeys);

      // convert bools
      comparison.isExisting = comparison.isExisting === '1';
    } catch (err) {
      throw new Error('Unable to make a valid version comparison.');
    }

    return comparison;
  }

  async function getVersion(context, version) {
    let ver;

    if (!version) {
      throw new InvalidInput({
        message: 'The version is a required field.'
      });
    }

    try {
      const rows = await getVersions(context, { version });
      ver = _.head(rows);
    } catch (err) {
      // throw handled below
    }

    if (!ver) {
      throw new Error(
        `Unable to retrieve platform version information for ${version}.`
      );
    }

    return ver;
  }

  async function getVersions(context, args) {
    const where = [];
    const values = [];

    if (args.version) {
      mainUtil.addSqlWhere('version', args.version, where, values);
    }

    const selectColumns = mainUtil.makeSelectClause(aiWAREVersionColumns);
    let sql = `
      SELECT 
        ${selectColumns} 
      FROM 
        ${aiWAREVersionTableName}`;

    if (where.length > 0) {
      sql += `\n WHERE ${where.join(' AND ')}`;
    }

    const orderBy =
      aiWAREVersionOrderByMap[args.orderBy] ||
      aiWAREVersionOrderByMap.createdAt;
    const orderDir =
      orderDirectionMap[args.orderDirection] || orderDirectionMap.desc;

    sql += `\n ORDER BY ${orderBy} ${orderDir}`;

    if (orderBy === aiWAREVersionOrderByMap.installedAt) {
      sql += ` NULLS LAST`;
    }

    if (Number.isInteger(args.limit)) {
      values.push(args.limit);
      sql += `\n LIMIT \$${values.length}`;
    }

    if (Number.isInteger(args.offset)) {
      values.push(args.offset);
      sql += `\n OFFSET \$${values.length}`;
    }

    try {
      return await dbRead.map(sql, values, mapper.camelizeRootKeys);
    } catch (err) {
      logger.error('Unable to retrieve the platform versions.', err);
      throw new Error('Unable to retrieve the platform versions.');
    }
  }

  async function getAIWAREVersionList(context, args) {
    let response = {
      aiWAREVersionList: {}
    };

    try {
      const results = await getVersions(context, args);
      response.aiWAREVersionList = mainUtil.toPage(args, results);
    } catch (err) {
      logger.error('Unable to retrieve the platform version list.', err);
      throw new Error('Unable to retrieve the platform version list.');
    }

    return response;
  }

  function _getInstanceLoginConfigurationColumnData(
    context,
    inputLoginConfig,
    isUpdate = false
  ) {
    const { userInfo, tokenInfo } = context.requestContext;
    let userId =
      _.get(userInfo, 'userId') ||
      _.get(tokenInfo, 'userId') ||
      '00000000-0000-0000-0000-000000000000';
    const {
      name,
      slug,
      logo,
      buttonColor,
      buttonTextColor,
      enabled,
      hideVeritoneBranding
    } = inputLoginConfig;

    const loginButtonStyle = {
      buttonColor,
      buttonTextColor
    };

    const columnData = {
      name,
      slug,
      logo,
      login_button_style: loginButtonStyle,
      modified_by: userId,
      enabled,
      hide_veritone_branding: hideVeritoneBranding
    };

    if (!isUpdate) {
      columnData.created_by = userId;
    }

    return columnData;
  }

  async function getInstanceLoginConfigurations(args) {
    let { limit, offset } = args || {};
    const sqlArgs = [];
    let loginConfigurations = [];

    const selectColumns = mainUtil.makeSelectClause(loginConfigColumns);

    let sql = ` 
        SELECT 
          ${selectColumns} 
        FROM 
          ${loginConfigurationTableName}
        WHERE
          organization_id IS NULL
    `;

    // Pagination
    if (!Number.isInteger(limit)) {
      limit = 30;
    }
    if (!Number.isInteger(offset)) {
      offset = 0;
    }

    sqlArgs.push(limit);
    sql += ` LIMIT \$${sqlArgs.length}`;

    sqlArgs.push(offset);
    sql += ` OFFSET \$${sqlArgs.length}`;

    try {
      const results = await dbReadLoginConfig.map(
        sql,
        sqlArgs,
        mapper.mapLoginConfiguration
      );

      loginConfigurations = mainUtil.toPage({ limit, offset }, results);
    } catch (err) {
      logger.error(
        'Unable to retrieve the instance-level login configurations.',
        err
      );
      throw new Error(
        'Unable to retrieve the instance-level login configurations.'
      );
    }

    return loginConfigurations;
  }

  async function createInstanceLoginConfiguration(context, inputLoginConfig) {
    const columnData = _getInstanceLoginConfigurationColumnData(
      context,
      inputLoginConfig
    );

    const { sql, values } = mainUtil.makeInsertSql(
      'public.login_configuration',
      columnData,
      loginConfigColumns
    );

    return await dbWriteLoginConfig.oneOrNone(
      sql,
      values,
      mapper.mapLoginConfiguration
    );
  }

  async function updateInstanceLoginConfiguration(
    context,
    inputLoginConfig,
    querySlug
  ) {
    const columnData = _getInstanceLoginConfigurationColumnData(
      context,
      inputLoginConfig,
      true
    );

    const { sql, values } = mainUtil.makeUpdateSql(
      'public.login_configuration',
      columnData,
      loginConfigColumns,
      'slug = $1',
      1
    );

    values.unshift(querySlug);

    return await dbWriteLoginConfig.oneOrNone(
      sql,
      values,
      mapper.mapLoginConfiguration
    );
  }

  async function deleteInstanceLoginConfiguration(context, args) {
    const { slug } = args;

    const sql = `
      DELETE FROM public.login_configuration
      WHERE
        slug = $1 AND organization_id IS NULL
      RETURNING
        slug,
        name
    `;
    const values = [slug];

    const res = await dbWriteLoginConfig.oneOrNone(
      sql,
      values,
      mapper.camelizeRootKeys
    );

    if (!res) {
      throw new errors.NotFound({
        message:
          'Instance Login configuration associated with the provided slug not found.',
        data: {
          slug
        }
      });
    }

    return {
      id: res.slug,
      message: `Instance Login Configuration (slug: ${res.slug}, name: '${res.name}') has been deleted`
    };
  }

  const reversedEventsMap = {};
  Object.keys(eventsMap).forEach((key) => {
    reversedEventsMap[eventsMap[key].event] = key;
  });

  const assembleResponse = (events, schemaEventTypes) => {
    return events
      .map((ev) => reversedEventsMap[ev])
      .filter((ev) => schemaEventTypes.find((sEv) => sEv.name === ev));
  };

  async function updateInstanceAuditLogConfig(_ctx, args, info) {
    const { userInfo, tokenInfo } = _ctx.requestContext;

    let userId = _.get(userInfo, 'userId') || _.get(tokenInfo, 'userId');
    const event = {
      serviceName: SERVICE_NAME,
      id: uuidv4(),
      updatedBy: userId,
      updatedAt: new Date().toISOString()
    };

    const emitEvent = (status, err = null) => {      
      let defaultMessage = !err ? `Updated the audit log configuration` : `Failed to update the audit log configuration`;            
      const payload = {
        ...event,
        actionInfo: messageUtil.buildActionInfo(
          null,
          err,
          eventsMap.AuditLogConfigChange.action,
          status,
          defaultMessage
        )
      };
      serviceContext.messageUtil.emitPublicEvent(
        eventsMap.AuditLogConfigChange.name,
        SYSTEM_APPLICATION_ID,
        _ctx,
        payload
      );
    };

    const { addAuditEvents = [], removeAuditEvents = [] } = args;
    if (_.intersection(addAuditEvents, removeAuditEvents).length > 0) {
      emitEvent(
        'failure',
        { statusCode: 400 },
        'Cannot add and remove the same event in the same request'
      );
      throw new InvalidInput({
        message: 'Cannot add and remove the same event in the same request.'
      });
    }
    const unsupportedEvents = [];
    function filterEvents(ev) {
      if (!eventsMap[ev]) {
        emitEvent(
          'failure',
          { statusCode: 400 },
          `Event ${ev} is not found in the events map`
        );
        logger.error(
          `Event ${ev} is not found in the events map`
        );
        unsupportedEvents.push(ev);
        return null;
      } else {
        return ev;
      }
    }

    const eventsToRemove = removeAuditEvents
      .filter(filterEvents)
      .map((ev) => eventsMap[ev].event);

    const eventsToAdd = addAuditEvents
      .filter(filterEvents)
      .map((ev) => eventsMap[ev].event);
    if (unsupportedEvents.length > 0) {
      emitEvent(
        'failure',
        { statusCode: 400 },
        `One or more events are not supported for audit logging`
      );
      throw new InvalidInput({
        message: `One or more events are not supported for audit logging: ${unsupportedEvents.join(
          ', '
        )}. Please remove them from the request and try again.`
      });
    }
    if (eventsToAdd.length === 0 && eventsToRemove.length === 0) {
      emitEvent(
        'failure',
        { statusCode: 400 },
        `None of the provided events is not supported for audit logging`
      );
      throw new InvalidInput({
        message: `None of the provided events is not supported for audit logging: ${[
          ...addAuditEvents,
          removeAuditEvents
        ].join(', ')}`
      });
    }

    let sql = `
        WITH updated_events AS (
          SELECT ARRAY(
              SELECT DISTINCT event
              FROM unnest(audit_config.configured_events || $2::text[]) AS event
              WHERE event NOT IN (SELECT unnest($1::text[]))
              AND NOT event = ANY(audit_config.baseline_events)
          ) AS updated_configured_events
          FROM aiware.audit_config
        )
        UPDATE aiware.audit_config
        SET configured_events = updated_events.updated_configured_events
        FROM updated_events
        RETURNING baseline_events, configured_events;`;
    const auditConfig = await dbWrite.one(
      sql,
      [eventsToRemove, eventsToAdd],
      mapper.camelizeRootKeys
    );
    const { baselineEvents = [], configuredEvents = [] } = auditConfig;
    emitEvent('success');
    const schemaEventNames = _.get(
      info,
      'schema._typeMap.EventNameEnum._values',
      []
    );
    return {
      immutableEvents: assembleResponse(baselineEvents, schemaEventNames),
      configurableEvents: assembleResponse(configuredEvents, schemaEventNames)
    };
  }

  const canExportLogsOlderThan12Months = _.get(
    config,
    'featureFlags.canExportLogsOlderThan12Months',
    true
  );
  async function instanceAuditLogConfig(_ctx, _args, info) {
    const sql = `
      SELECT
        baseline_events,
        configured_events
      FROM
        aiware.audit_config
      LIMIT 1;`;
    const auditConfig = await dbRead.one(sql, {}, mapper.camelizeRootKeys);
    const { baselineEvents = [], configuredEvents = [] } = auditConfig;
    const schemaEventNames = _.get(
      info,
      'schema._typeMap.EventNameEnum._values',
      []
    );
    return {
      immutableEvents: assembleResponse(baselineEvents, schemaEventNames),
      configurableEvents: assembleResponse(configuredEvents, schemaEventNames)
    };
  }

  function validateExportRequestDateTimeFilter(dateTimeFilter) {
    if (!dateTimeFilter) return;

    const { fromDateTime, toDateTime } = dateTimeFilter;
    if (!fromDateTime || !toDateTime) {
      throw new InvalidInput({
        message: 'fromDateTime and toDateTime are required fields.'
      });
    }

    if (
      !moment(new Date(fromDateTime)).isValid() ||
      !moment(new Date(toDateTime)).isValid()
    ) {
      throw new InvalidInput({
        message: 'fromDateTime and toDateTime must be valid date strings.'
      });
    }

    if (moment(new Date(toDateTime)).isBefore(new Date(fromDateTime))) {
      throw new InvalidInput({
        message: 'fromDateTime must occur before toDateTime.'
      });
    }

    if (
      !canExportLogsOlderThan12Months &&
      moment(new Date(toDateTime)).diff(
        moment(new Date(fromDateTime)),
        'months',
        true
      ) > 12
    ) {
      throw new InvalidInput({
        message: 'Time range filter must not exceed 12 months.'
      });
    }
  }

  async function validateExportRequestOrgAccess(ctx, inputOrgId, userOrgId) {
    try {
      const isSuperAdmin = resUtil.isSuperAdmin(ctx._authInfo);
      if (!isSuperAdmin) {
        if (userOrgId.toString() !== inputOrgId.toString()) {
          throw new NotAllowed({
            message: `User is not allowed to export audit logs for organization ${inputOrgId}.`
          });
        }
      }
      await serviceContext.dal.organization.getOrganization(ctx, {
        id: inputOrgId
      });
    } catch (err) {
      logger.error(
        `Unable to validate export request org access for organizationId ${inputOrgId}.`,
        err
      );
      throw new ServiceFailure({
        message: `Unable to validate export request org access for organizationId ${inputOrgId}.`
      });
    }
  }

  async function persistAuditLogExportRequest(
    ctx,
    args,
    requestorId,
    mailboxId
  ) {
    const requestId = uuidv4();
    const payloadPublicEvent = {
      auditLogExportRequestId: requestId,
      requestorId: requestorId,
      createdDateTime: new Date().toISOString(),
      filters: args
    };

    try {
      const event = {
        id: uuidv4(),
        auditLogExportRequestId: requestId,
        type: 'export',
        event: 'audit_log_export_request',
        filters: args,
        mailboxId: mailboxId
      };

      const columnData = {
        id: requestId,
        filters: args,
        status: 'pending',
        requestor_id: requestorId,
        downloadUrl: null
      };

      const selectData = {
        id: null,
        status: null,
        filters: null,
        download_url: null,
        requestor_id: null
      };

      const { sql, values } = mainUtil.makeInsertSql(
        'job_new.audit_log_export_request',
        columnData,
        selectData
      );

      const res = await serviceContext.dbConnections['core'].write.map(
        sql,
        values,
        mapper.camelizeRootKeys
      );

      event.requestToken =
        ctx._authInfo.token ||
        ctx._authInfo.tokenId ||
        ctx.requestContext.authToken;

      messageUtil.emitEvent(event, messageUtil.topics('EVENTS'));
      emitExportRequestPublicEvent(
        ctx,
        payloadPublicEvent,
        eventsMap.AuditLogExportCreate,
        null,
        `Created an audit log export ${res[0].id}`
      );
      return res;
    } catch (error) {
      emitExportRequestPublicEvent(
        ctx,
        payloadPublicEvent,
        eventsMap.AuditLogExportCreate,
        error,
        'Failed to create an audit log export'
      );
      throw error;
    }
  }

  function emitExportRequestPublicEvent(ctx, payload, event, error, message) {
    const body = {
      ...payload,
      actionInfo: messageUtil.buildActionInfo(
        payload.auditLogExportRequestId || payload.orgId,
        error,
        event.action,
        !error ? 'success' : 'failure',
        message,
        event.targetType
      )
    };
    serviceContext.messageUtil.emitPublicEvent(
      event.name,
      SYSTEM_APPLICATION_ID,
      ctx,
      body
    );
  }

  function whereOrAnd(sql) {
    return sql.includes('WHERE') ? ' AND' : ' WHERE';
  }

  async function getAuditLogExportRequestObjectsForOrg(
    ctx,
    args,
    queryById,
    internalUse,
    isCreationProcess
  ) {
    let responseBodyFormatted;
    const clientInfo = resUtil.getClientInfo(ctx);
    let target = {};
    try {
      if (queryById && (_.isNil(args.id) || !validator.isUUID(args.id))) {
        throw new InvalidInput({
          message: 'id must be a valid UUID.'
        });
      }
      const { __ignoreParamsForValidation = [] } = args;
      for (const param of __ignoreParamsForValidation) {
        delete args[param];
      }      
      const organizationId = _.get(args, 'organizationId');
      if (organizationId) {
        await validateExportRequestOrgAccess(
          ctx,
          organizationId,
          clientInfo.org
        );
      } else {
        args.organizationId = clientInfo.org;
      }
      // skip pagination if data retrieval is for internal use (for comparison)
      if (!internalUse || args.id) {
        if (!args.limit || args.limit > 30 || args.limit < 1) {
          args.limit = 30;
        }
        if (!args.offset || args.offset < 0) {
          args.offset = 0;
        }
      }
      const values = [];
      let sql = `
        SELECT * FROM job_new.audit_log_export_request`;

      if (args.organizationId) {
        values.push(args.organizationId);
        sql += `${whereOrAnd(sql)} filters->>'organizationId' = $${
          values.length
        }::text`;
      }
      if (args.id) {
        values.push(args.id);
        sql += `${whereOrAnd(sql)} id = $${values.length}`;
      }
      if (args.statuses) {
        values.push(args.statuses.map((s) => reverseStatusLookup(s)));
        sql += `${whereOrAnd(sql)} status = ANY($${values.length}::text[])`;
      }
      if (args.limit) {
        values.push(args.limit);
        sql += ` LIMIT $${values.length}`;
        values.push(args.offset);
        sql += ` OFFSET $${values.length}`;
      }
      const res = await serviceContext.dbConnections['core'].read.map(
        sql,
        values,
        mapper.camelizeRootKeys
      );

      if (res.length === 0) {
        if (args.id) {
          throw new NotFound({
            message: `Could not find export request with ID ${args.id} ${
              args.organizationId
                ? `for organization ${args.organizationId}`
                : ''
            }.`
          });
        }
      }

      if (args.id) {
        responseBodyFormatted = await formatAuditLogExportRequestResponse(
          res[0]
        );
        target.id = responseBodyFormatted.id;
        target.filters = responseBodyFormatted.filters;
      } else {
        responseBodyFormatted = mainUtil.toPage(
          args,
          await Promise.all(res.map(formatAuditLogExportRequestResponse))
        );
        target.orgId = args.organizationId;
        target.statuses = args.statuses;
      }

      emitAuditLogExportQueryPublicEvent(
        ctx,
        target,
        (clientInfo.userName || clientInfo.organizationName).trimEnd(),
        clientInfo.id,
        null,
        isCreationProcess
      );
      return responseBodyFormatted;
    } catch (error) {
      args.id ? (target.id = args.id) : (target.orgId = args.organizationId);
      emitAuditLogExportQueryPublicEvent(
        ctx,
        target,
        (clientInfo.userName || clientInfo.organizationName).trimEnd(),
        clientInfo.id,
        error,
        isCreationProcess
      );
      throw error;
    }
  }

  function emitAuditLogExportQueryPublicEvent(
    ctx,
    target,
    userName,
    requestorId,
    error,
    isCreationProcess
  ) {
    if (!isCreationProcess) {
      // only emit when it's not a creation process
      let payloadPublicEvent = {
        createdDateTime: new Date().toISOString(),
        requestorId
      };
      let eventMessage = '';
      if (target.id) {
        payloadPublicEvent.auditLogExportRequestId = target.id;
        const isInvalidIdError = error?.name === 'invalid_input' || error?.name === 'not_found';
        eventMessage = _.isEmpty(error)
        ? `Requested the audit log export ${target.id}`
        : `Failed to request the audit log export ${isInvalidIdError ? undefined : target.id}`;
      } else {
        payloadPublicEvent.orgId = target.orgId;
        eventMessage += _.isEmpty(error)
          ? `Requested a list of audit log exports for organization ${target.orgId}`
          : `Failed to request a list of audit log exports for organization ${target.orgId}`;
      }

      emitExportRequestPublicEvent(
        ctx,
        payloadPublicEvent,
        eventsMap.AuditLogExportQuery,
        error,
        eventMessage
      );
    }
  }

  // helper function to format incoming export request timestamps to unix
  function roundToSecond(dateTime) {
    const date = new Date(dateTime);
    date.setMilliseconds(0);

    return date.toISOString();
  }

  // helper function to compare incoming export request with existing requests within the same organization
  function compareAuditLogExportRequest(newRequest, existingRequests) {
    let existingRequestId;
    // format incoming filter's date string to match db's unix timestamp
    const formattedRequest = {
      ...newRequest,
      dateTimeFilter: {
        fromDateTime: roundToSecond(newRequest.dateTimeFilter.fromDateTime),
        toDateTime: roundToSecond(newRequest.dateTimeFilter.toDateTime)
      }
    };
    for (const request of existingRequests) {
      if (_.isEqual(request.filters, formattedRequest)) {
        existingRequestId = request.id;
        break;
      }
    }
    if (existingRequestId) {
      throw new Error(
        `An export request with the same filters already exists. Request ID: ${existingRequestId}`
      );
    }
  }

  async function createAuditLogExportRequest(ctx, args = {}) {
    const isSuperAdmin = resUtil.isSuperAdmin(ctx._authInfo);
    const clientInfo = resUtil.getClientInfo(ctx);
    try {
      // validate input
      const dateTimeFilter = _.get(args, 'dateTimeFilter');
      validateExportRequestDateTimeFilter(dateTimeFilter);

      const organizationId = _.get(args, 'organizationId');
      if (organizationId) {
        await validateExportRequestOrgAccess(ctx, organizationId, clientInfo.org);
      } else {
        // if no organizationId is provided, use the requestor's organization
        args.organizationId = clientInfo.org;
      }

      // check if the same request already exists
      const { records } = await getAuditLogExportRequestObjectsForOrg(
        ctx,
        {
          organizationId: args.organizationId,
          statuses: ['PENDING', 'IN_PROGRESS']
        },
        false,
        true,
        true
      );
      const resolvedRecords = await Promise.all(records);
      if (resolvedRecords.length > 0) {
        throw new Error(
          `An export request for this organization already exists and it is in ${resolvedRecords[0].status} status. 
        Request ID: ${resolvedRecords[0].id}. Please wait for the current request to complete or cancel it before creating a new one.`
        );
      }

      const mailboxOrgId = isSuperAdmin
        ? organizationId || clientInfo.org
        : clientInfo.org;
      const options = {
        userId: clientInfo.id,
        name: _.get(
          serviceContext,
          'config.mailbox.reservedNames.exportStatusMailbox'
        ),
        organizationId: mailboxOrgId
      };

      const mailbox = await serviceContext.bll.mailbox.createMailboxIfNotExists(
        ctx,
        options,
        true
      );

      // persist the request if no duplicate exists after comparison
      const requestObjects = await persistAuditLogExportRequest(
        ctx,
        args,
        clientInfo.id,
        mailbox.id
      );

      return formatAuditLogExportRequestResponse(requestObjects[0]);
    } catch (err) {
      const payloadPublicEvent = {        
        requestorId: clientInfo.id,
        createdDateTime: new Date().toISOString(),
        filters: args
      };
      emitExportRequestPublicEvent(
        ctx,
        payloadPublicEvent,
        eventsMap.AuditLogExportCreate,
        err,
        'Failed to create an audit log export'
      );
      throw err;
    } 
  }

  async function cancelAuditLogExportRequestDB(id, organizationId) {
    let sql = `
      UPDATE job_new.audit_log_export_request
      SET status = 'cancelled'
      WHERE id = $1 AND status = ANY(ARRAY['pending', 'in_progress'])
    `;
    const values = [id];
    if (organizationId) {
      sql += ` AND filters->>'organizationId' = $2::text`;
      values.push(organizationId);
    }
    sql += ` RETURNING *`;
    const resp = await serviceContext.dbConnections['core'].write.query(
      sql,
      values
    );
    return resp.length > 0;
  }

  async function cancelAuditLogExportRequest(ctx, args) {
    const isSuperAdmin = resUtil.isSuperAdmin(ctx._authInfo);
      const clientInfo = resUtil.getClientInfo(ctx);
      const { id } = args;
      const payloadPublicEvent = {
        auditLogExportRequestId: id,
        requestorId: clientInfo.id,
        createdDateTime: new Date().toISOString()
      };
    try {
      if (!id) {
        throw new InvalidInput({
          message: 'The id is a required field.'
        });
      }
      if (!validator.isUUID(id)) {
        throw new InvalidInput({
          message: 'The id must be a valid UUID.'
        });
      }
      let cancelResp;
      if (isSuperAdmin) {
        // cancel request regardless of the org it belongs to
        cancelResp = await cancelAuditLogExportRequestDB(id);
      } else {
        // validate requestor's access to the request's organization
        const organizationId = _.get(clientInfo, 'org');
        cancelResp = await cancelAuditLogExportRequestDB(id, organizationId);
      }

      if (cancelResp === true) {
        emitExportRequestPublicEvent(
          ctx,
          payloadPublicEvent,
          eventsMap.CancelAuditLogExport,
          null,
          `Cancelled the audit log export ${id}`
        );
      } else {
        emitExportRequestPublicEvent(
        ctx,
        payloadPublicEvent,
        eventsMap.CancelAuditLogExport,
        { error: 'cannot_cancel' },
        `Failed to cancel the audit log export ${id} because it is not in a cancellable state`
      );
      }
      return cancelResp;
    } catch (err) {
      const isInvalidIdError = err?.name === 'invalid_input';
      emitExportRequestPublicEvent(
        ctx,
        payloadPublicEvent,
        eventsMap.CancelAuditLogExport,
        err,
        `Failed to cancel the audit log export ${isInvalidIdError ? undefined : id}`
      );
      throw err;
    }
  }

  return {
    setPlatformProperties,
    addPlatformVersion,
    setCurrentPlatformVersion,
    getAIWAREVersion,
    _getAIWAREVersionHistorySql,
    getAIWAREVersionHistory,
    getPlatformProperties,
    getAIWAREVersionList,
    getInstanceLoginConfigurations,
    createInstanceLoginConfiguration,
    updateInstanceLoginConfiguration,
    deleteInstanceLoginConfiguration,
    updateInstanceAuditLogConfig,
    instanceAuditLogConfig,
    reversedEventsMap,
    createAuditLogExportRequest,
    getAuditLogExportRequestObjectsForOrg,
    cancelAuditLogExportRequest
  };
};
