INSERT INTO public.market_geography_type (
	market_geography_type_id,
	market_geography_type_name
) values (
	3, 'Canada'
) on conflict do nothing;

SELECT setval('public.market_market_id_seq', 213, true);

INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Toronto, ON', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Oshawa, ON', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('St. Catharines–Niagara Falls, ON', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Sherbrooke, QC', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Nanaimo, BC', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Vancouver, BC', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Halifax, NS', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Saskatoon, SK', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Sault Ste. Marie, ON', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Barrie, ON', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Sarnia, ON', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Trois-Rivières, QC', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Chatham, ON', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('St. Thomas, ON', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Shawinigan, QC', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Leduc, AB', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Prince George, BC', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Beloeil, QC', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Courtenay, BC', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Spruce Grove, AB', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Stratford, ON', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Saint-Georges, QC', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Georgetown, ON', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Rimouski, QC', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Stouffville, ON', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Edmonton, AB', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Kitchener, ON', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('London, ON', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Châteauguay, QC', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Quebec City, QC', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('St. John''s, NL', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Kingston, ON', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Chicoutimi–Jonquière, QC', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Red Deer, AB', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Peterborough, ON', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Montreal, QC', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Winnipeg, MB', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Victoria, BC', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Regina, SK', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Kelowna, BC', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Kanata, ON', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Sudbury, ON', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Lethbridge, AB', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('North Bay, ON', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Brandon, MB', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Salaberry-de-Valleyfield, QC', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Campbell River, BC', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Mission, BC', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Bradford, ON', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Val-d''Or, QC', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Medicine Hat, AB', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Prince Albert, SK', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Quispamsis–Rothesay, NB', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Saint John, NB', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Victoriaville, QC', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Penticton, BC', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Vernon, BC', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Calgary, AB', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Ottawa–Gatineau, ON-QC', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Abbotsford, BC', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Moncton, NB', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Saint-Jérôme, QC', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Kamloops, BC', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Milton, ON', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('White Rock, BC', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Belleville, ON', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Drummondville, QC', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Airdrie, AB', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Hamilton, ON', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Windsor, ON', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Guelph, ON', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Brantford, ON', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Thunder Bay, ON', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Saint-Jean-sur-Richelieu, QC', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Chilliwack, BC', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Fort McMurray, AB', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Welland–Pelham, ON', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Fredericton, NB', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Bowmanville, ON', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Cape Breton–Sydney, NS', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Bolton, ON', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Midland, ON', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Grande Prairie, AB', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Granby, QC', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Cornwall, ON', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Joliette, QC', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Moose Jaw, SK', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Lloydminster, AB-SK', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Okotoks, AB', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Woodstock, ON', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Orangeville, ON', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Cochrane, AB', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Saint-Hyacinthe, QC', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Charlottetown, PE', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Sorel, QC', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Leamington, ON', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Orillia, ON', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Timmins, ON', '', 3);
INSERT INTO public.market (market_name, market_code, market_geography_type_id) VALUES('Keswick–Elmhurst Beach, ON', '', 3);
